### ISSUE TITLE
Clip with Polygon causes IndexError: list index out of range

### ISSUE THREAD

**Issue by kostastheocharoulis** [anitagraser/movingpandas#104]
I am trying to  add the clip approach in the  2-ship-data.ipynb notebook by adding  below _the get_intersecting chunk_ 
the following: 

```
all_trajectories = traj_collection.trajectories
arrivals = [ traj.clip(area_of_interest) for traj in all_trajectories ] 
```

And I  am getting the following error  &  I cannot understand why  ? 

>      15        if type(row['spatial_intersection']) == LineString:
>      16         -> pt0 = Point(row['spatial_intersection'].coords[0])
>      17             ptn = Point(row['spatial_intersection'].coords[-1])
>      18             t = row['prev_t']
> 
> **IndexError: list index out of range**

**Comment by anitagraser** [comment]
Dear Kostas, please provide a minimum example (code & data) that reproduces the issue.

**Comment by kostastheocharoulis** [comment]
Thanks for your quick response . Attached you ll find the code. The only difference with the initial version is the addition of the above lines 
[Example.zip](https://github.com/anitagraser/movingpandas/files/6214031/Example.zip)

**Comment by anitagraser** [comment]
Thanks, I can reproduce the issue. Additionally, there is clearly an issue with clipping not including all expected results, as can be seen in this example: 

```
arrivals = traj_collection.clip(area_of_interest) 
print("Cipping resulted in {} trajectories".format(len(arrivals)))
intersecting.hvplot() + arrivals.hvplot()
```

![image](https://user-images.githubusercontent.com/590385/112697970-f27e6c00-8e88-11eb-9068-ed50d7b43a89.png)

For reference: https://github.com/anitagraser/movingpandas-examples/blob/main/analysis-examples/2-ship-data.ipynb

**Comment by anitagraser** [comment]
```
traj_collection.get_trajectory(244886000).clip(area_of_interest)
plotted_area_of_interest = GeoDataFrame(pd.DataFrame([{'geometry': area_of_interest, 'id': 1}]), crs=wgs84).hvplot(geo=True, color='yellow', alpha=0.5)
traj_collection.get_trajectory(244886000).hvplot() * plotted_area_of_interest
```

![image](https://user-images.githubusercontent.com/590385/112699617-80a82180-8e8c-11eb-968c-7c213136c880.png)

**Comment by anitagraser** [comment]
There is no error and results look better with the following polygon:

`area_of_interest = Polygon([(11.90, 57.695), (11.90, 57.685), (11.903, 57.685), (11.903, 57.695), (11.90, 57.695)])`

**Comment by kostastheocharoulis** [comment]
Thanks Anita for the update , I have noticed the same , that the issue is related to the polygon selected area .
However  I havent understood in which cases  it returns an error in line  Point(row['spatial_intersection'].coords[0]) of movingpandas\overlay.py

**Comment by anitagraser** [comment]
I haven't been able to narrow it down any further either. I think it is a numerical issue.

**Comment by wendellwt** [comment]
I've notice something similar.  tc.get_intersecting() and tc.clip() work fine if the polygon is a "bounding box" shape, that is with edges that are vertical and horizontal.  If the edges are irregular, tc.get_intersecting() works as expected, but tc.clip() either fails as @kostastheocharoulis described, or it produces 0 results.  Am I using get_intersecting() and clip() correctly?
BTW, thank you for a terrific library.
![image](https://user-images.githubusercontent.com/31513903/112762427-a4bf4c00-8fcd-11eb-81ba-47c94e2e6ada.png)


[clip.zip](https://github.com/anitagraser/movingpandas/files/6217764/clip.zip)

**Comment by kostastheocharoulis** [comment]
Hi Anita 

I thing that the issue comes from the following line : 
`possible_matches['spatial_intersection'] = possible_matches.intersection(polygon)`

as it returns a dataframe column with an empty spatial_intersection as you can see below : 

> t,Timestamp,MMSI,NavStatus,SOG,COG,Name,ShipType,geometry,prev_pt,t,prev_t,line,spatial_intersection
> 2017-07-05 04:38:42,05/07/2017 04:38:42,244886000,Under way using engine,9.0,53.0,ASPEN,Cargo,POINT (11.90285 57.691733),POINT (11.8993 57.690433),2017-07-05 04:38:42,2017-07-05 04:37:42,"LINESTRING (11.8993 57.690433, 11.90285 57.691733)","LINESTRING (11.90047743663292 57.69086417397826, 11.90224549092865 57.69151163048092)"
> **2017-07-05 04:39:42,05/07/2017 04:39:42,244886000,Under way using engine,9.2,50.0,ASPEN,Cargo,POINT (11.906533 57.693417),POINT (11.90285 57.691733),2017-07-05 04:39:42,2017-07-05 04:38:42,"LINESTRING (11.90285 57.691733, 11.906533 57.693417)",LINESTRING EMPTY**

which causes the issue _the list index out of range error_   as there are n't any coords) .

So I would like to ask  from business  perspective first you calculate the potentially_intersecting_lines and based on this result you calculate the interesction with  polygon linesbased.   right ? 

The geopandas [document](https://geopandas.readthedocs.io/en/latest/docs/reference/api/geopandas.GeoSeries.intersection.html)  indicates that  you can check two GeoSeries against each other, row by row. So as it is defined the process the potential matches may not interract with polygon and thus I think a check of empty linestring is required in the calculation of spatial_intersections

**Comment by anitagraser** [comment]
> I think a check of empty linestring is required in the calculation of spatial_intersections

Sure, this will make the error go away but - as shown in the screenshots above - the clip results are incomplete and we will not get the missing segments by just throwing away rows.

**Comment by anitagraser** [comment]
> Am I using get_intersecting() and clip() correctly?

Yes, you're using them as intended. Thank you for providing this small reproducible example. Let's see if this example can be turned into a unit test that proofs this issue.

**Comment by anitagraser** [comment]
We have a test, now we need a fix: 

```
def test_clipping_issue(self):
    polygon = Polygon([(-92.98830, 35.38896), (-92.35109, 33.96139), (-93.27393, 33.61437),
                       (-93.99904, 34.88572), (-92.98830, 35.38896)])
    traj = make_traj([
        Node(-92.00000, 35.35000, 2020, 8, 5, 21, 33),
        Node(-92.10000, 35.30000, 2020, 8, 5, 21, 34),
        Node(-92.48333, 35.05000, 2020, 8, 5, 21, 38),
        Node(-92.68333, 34.95000, 2020, 8, 5, 21, 40),
        Node(-92.80000, 34.86667, 2020, 8, 5, 21, 41),
        Node(-93.15000, 34.66667, 2020, 8, 5, 21, 44),
        Node(-93.31667, 34.55000, 2020, 8, 5, 21, 45),
        Node(-93.66667, 34.35000, 2020, 8, 5, 21, 48),
        Node(-93.88333, 34.20000, 2020, 8, 5, 21, 50),
        Node(-94.00000, 34.16904, 2020, 8, 5, 21, 51)
    ])
    result = traj.clip(polygon)
    assert len(result) == 1
```

**Comment by anitagraser** [comment]
> I think a check of empty linestring is required in the calculation of spatial_intersections

You're right. That did the trick.

![image](https://user-images.githubusercontent.com/590385/112862271-e3c8cc80-90b5-11eb-938a-7153ec38c2ce.png)

**Comment by wendellwt** [comment]
Thank you!! It works fine now.
