### ISSUE TITLE
Exporting trajectory data to other formats and measuring distance between stops

### ISSUE THREAD

**Issue by WailerG** [anitagraser/movingpandas#105]
I got stuck when it comes to the following:
1. Extracting trajectory data into excel or csv or data format
2. Measuring the distance between points/stops and extracting it to excel/csv.
3. Extracting distances of trips excluding stops to excel/csv

**Comment by anitagraser** [comment]
>Extracting trajectory data into excel or csv or data format

Which information exactly would you want to export to csv? Do all three questions refer to trajectory length? 

> Measuring the distance between points/stops

Do you mean the euclidean distance or the distance along the trajectory?

**Comment by WailerG** [comment]
Exporting:
(1) stops based on a set of criteria
(2) trips between the stops
(3) the distance along the trajectory
<img width="462" alt="Screenshot 2021-03-29 at 19 48 00" src="https://user-images.githubusercontent.com/80400091/112878000-b553ed00-90c7-11eb-920e-a73233b704ad.png">

**Comment by anitagraser** [comment]
Sounds like this would be mostly covered by #98

**Comment by anitagraser** [comment]
@WailerG can you provide an example of how the resulting CSVs should look like? Do you want one line per trajectory or do you want one line per location point?

**Comment by anitagraser** [comment]
Closed for lack of feedback.
