### ISSUE TITLE
stop algorithm sensitivity

### ISSUE THREAD

**Issue by Kersauson** [anitagraser/movingpandas#108]
Hello Anita,

Here is an "issue" that I found by playing with the interactive tutorial. I used the same time parameter that you did, 60 seconds, but slided the distance parameter : 10, 15, 50 and 100m. 
Here are the results : 

- **10 m** : 1 stop detected, max duration = 84 seconds
- **15 m** : 4 stops detected, max duration = 184 seconds
- **50 m** : 6 stops detected, max duration = 105 seconds
- **100 m** : 7 stops detected, max duration = 277 seconds

Here are the question I have from those results : 
- How do you explain that the maximum duration with the 50 meters radius is lower than the maximum duration of the 15 meters radius?
- Is there a rule for suppressing GPS points coming back in a stop (often the case in the vast heterogeneity of GPS patterns) but not part of a stop?
- Is there a rule in the algorithm for aggregating two stops very closed? In the stop detection litterature, it is shown that it is often necessary to aggregate two stops very closed by, as there is no parameter for fuzzyness.
- Would you say that 3 stops detected for only 3 meters difference in parameters is a proof that the sensitivity of your algorithm has to be tested?

Thanks for your answers!

Colin

**Comment by anitagraser** [comment]
> How do you explain that the maximum duration with the 50 meters radius is lower than the maximum duration of the 15 meters radius?

The implemented algorithm is rather simple. It does not perform any optimization to find the longest stops. Instead, it collects consecutive locations within the specified radius and then (once a location exceeds the radius) checks if the desired duration is exceeded. It would be interesting to dig deeper into the specific reason why the longest stop for radius=15 is not detected with radius=50. 

> Is there a rule for suppressing GPS points coming back in a stop (often the case in the vast heterogeneity of GPS patterns) but not part of a stop?

Please clarify what you mean with "suppressing". Currently, the algorithm on considers chronologically contiguous points (subtrajectories).

> Is there a rule in the algorithm for aggregating two stops very closed?

No but algorithmic improvements would be very welcome. 

> Would you say that 3 stops detected for only 3 meters difference in parameters is a proof that the sensitivity of your algorithm has to be tested?

Besides the algorithm and the parameter settings, input data characteristics, especially noise and reporting interval influence stop detection results. A systematic sensitivity analysis would be very welcome.

**Comment by anitagraser** [comment]
>It would be interesting to dig deeper into the specific reason why the longest stop for diameter=15 is not detected with diameter=50.

Of course, we also need to note that a stop diameter of 15m is highly questionable considering GPS location accuracy.

**Comment by Kersauson** [comment]
> Of course, we also need to note that a stop diameter of 15m is highly questionable considering GPS location accuracy.

Yes for sure it is questionable. Do you have any reference showing that GPS accuracy is higher than 15m?
In a GPS track, high inaccuracy tend to be filtered with a median filter or with a outlier detection algorithm.
Also, 15 meters walked in 60 seconds correspond to a speed of 0.9km.h-1, which is possible in moutainous areas (see tobler hiking function or naismith function, or irmisher and clarke more recent function)... meaning that even at that distance resolution, we would detect slow mobility and not stops (for stops of 1 minute which is, I think, very high level of expectation).

In my thesis I have ran a sensitivity analysis on stop detection for stdbscan (which doesnt act the same as your algorithm I believe), and I have shown that the optimal parameters are closed to 8m for distance threshold. But as stdbscan is density-based and your algo is based on sub-trajectories, we are not looking for the same pattern in the GPS tracks.

**Comment by anitagraser** [comment]
> Do you have any reference showing that GPS accuracy is higher than 15m?

Geolife data is certainly no more accurate than +/- 15m. However, other GPS tracking datasets may be more accurate, especially if they employ technology like DGPS common in precision agriculture and similar domains. 

> as stdbscan is density-based and your algo is based on sub-trajectories, we are not looking for the same pattern in the GPS tracks.

That's right. I can imagine some advantages of spatiotemporal density-based clustering but - as always - it's application dependent. 

> Also, 15 meters walked in 60 seconds correspond to a speed of 0.9km.h-1, which is possible in moutainous areas ...

Yes, if you are thinking specifically about human tracking data, these points should be considered. MovingPandas, however, is taking a more generic approach and other moving objects may require other parameter settings. That's why the user has to configure these parameters to fit their data and use case.

**Comment by anitagraser** [comment]
Closing as answered.
