### ISSUE TITLE
Problem working from postgis to geopandas to trajectory

### ISSUE THREAD

**Issue by bigcarto** [anitagraser/movingpandas#112]
I'm trying to use moving pandas to process GPS data stored on a PostGIS database.
I'm connecting to PostGIS with psycopg2
I load a table to a geodataframe with geopandas.
I loaded the geodataframe to trajectories and if I print the collection I get
TrajectoryCollection with 34 trajectories so it seems to be ok
I get the first trajectory with my_traj = traj_collection.trajectories[1]

Problem 1)
If I print (my_traj) I get an error
AttributeError: 'DataFrameGroupBy' object has no attribute 'geometry'

On PostGIS my geometry column is named geom, I tried to rename the geom to geometry on the geodataframe prior to creating the TrajectoryCollection, It seems to work but then I get two geomemetry fields, geom and geometry

If I print the trajectory again, I get this error.
AttributeError: 'numpy.int64' object has no attribute 'to_pydatetime'

Problem 2)
If I try to store speed with 
traj_collection.add_speed(overwrite=True)
I get an error message, the last line is 
AttributeError: 'float' object has no attribute 'total_seconds'

Could you help me to solve this problem?
Thanks!

**Comment by anitagraser** [comment]
Hi Jose. Please include your code to reproduce both issues. I'll then give it a try. In both cases, it seems like the GeoDataFrame columns are not what MovingPandas expects. Please also provide the schema of your PostGIS table and a small data sample exported to CSV which I can import into my local database.

**Comment by bigcarto** [comment]
Hello I found the solution, you were right the GeoDataFrame columns weren't right,
I changed the sql to get the data, instead of import geom column and changing the name of the column in geodataframe, now I selected the geom column as geometry.
Also imported the datetime column as t, instead of fecha (date in Spanish)

sql_puntos = "SELECT loc_gps.geom AS geometry, loc_gps.fecha AS t , id_barco_interno, loc_gps.id_dispositivo_gps FROM loc_gps WHERE fecha >  now() - interval '1 day'  ORDER BY loc_gps.id desc;"

Also, I wasn't defining the index properly.
Now it seems to run properly.

Thanks for the advice!

**Comment by anitagraser** [comment]
Great to hear that it works now.

**Comment by lucadelu** [comment]
Hi @anitagraser, 

I have the same problem but If I try to rename the geom column to geometry as @bigcarto did I got an error in GeoPandas

```
single_animal = "select geom, gps_data_animals_id, animals_id, acquisition_time as t from main.gps_data_animals where gps_data_animals.animals_id=10 and geom is not null;"
animal_df = gpd.GeoDataFrame.from_postgis(single_animal, con)
traj = mpd.Trajectory(animal_df, 1)
traj.get_geom_column_name()
  'geom'
traj.get_bbox()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-76341803138b> in <module>
----> 1 traj.get_bbox()

~/gitfem/euromammals/venv/lib/python3.9/site-packages/movingpandas-0.7rc1-py3.9.egg/movingpandas/trajectory.py in get_bbox(self)
    345             Bounding box values (minx, miny, maxx, maxy)
    346         """
--> 347         return self.to_linestring().bounds  # (minx, miny, maxx, maxy)
    348 
    349     def get_start_time(self):

~/gitfem/euromammals/venv/lib/python3.9/site-packages/movingpandas-0.7rc1-py3.9.egg/movingpandas/trajectory.py in to_linestring(self)
    249         """
    250         try:
--> 251             return point_gdf_to_linestring(self.df)
    252         except RuntimeError:
    253             raise RuntimeError("Cannot generate LineString")

~/gitfem/euromammals/venv/lib/python3.9/site-packages/movingpandas-0.7rc1-py3.9.egg/movingpandas/trajectory.py in point_gdf_to_linestring(df)
    788     """
    789     if len(df) > 1:
--> 790         return df.groupby([True] * len(df)).geometry.apply(
    791             lambda x: LineString(x.tolist())).values[0]
    792     else:

~/gitfem/euromammals/venv/lib/python3.9/site-packages/pandas/core/groupby/groupby.py in __getattr__(self, attr)
    750             return self[attr]
    751 
--> 752         raise AttributeError(
    753             f"'{type(self).__name__}' object has no attribute '{attr}'"
    754         )

AttributeError: 'DataFrameGroupBy' object has no attribute 'geometry'
```

when I try to rename geom in geometry I get error on GeoDataFrame
```
single_animal = "select geom as geometry, gps_data_animals_id, animals_id, acquisition_time as t from main.gps_data_animals where gps_data_animals.animals_id=10 and geom is not null;"
animal_df = gpd.GeoDataFrame.from_postgis(single_animal, con)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-8-2a9a8c0b83ba> in <module>
      1 single_animal = "select geom as geometry, gps_data_animals_id, animals_id, acquisition_time as t from main.gps_data_animals where gps_data_animals.animals_id=10 and geom is not null;"
----> 2 animal_df = gpd.GeoDataFrame.from_postgis(single_animal, con)

~/gitfem/euromammals/venv/lib/python3.9/site-packages/geopandas/geodataframe.py in from_postgis(cls, sql, con, geom_col, crs, index_col, coerce_float, parse_dates, params, chunksize)
    657         """
    658 
--> 659         df = geopandas.io.sql._read_postgis(
    660             sql,
    661             con,

~/gitfem/euromammals/venv/lib/python3.9/site-packages/geopandas/io/sql.py in _read_postgis(sql, con, geom_col, crs, index_col, coerce_float, parse_dates, params, chunksize)
    161             chunksize=chunksize,
    162         )
--> 163         return _df_to_geodf(df, geom_col=geom_col, crs=crs)
    164 
    165     else:

~/gitfem/euromammals/venv/lib/python3.9/site-packages/geopandas/io/sql.py in _df_to_geodf(df, geom_col, crs)
     63 
     64     if geom_col not in df:
---> 65         raise ValueError("Query missing geometry column '{}'".format(geom_col))
     66 
     67     geoms = df[geom_col].dropna()

ValueError: Query missing geometry column 'geom'
```

However with `geom` column I'm able to plot the date with plot() and hvplot() functions

**Comment by lucadelu** [comment]
I cannot use `geom as geometry` because I get the error reported before. Probably I should rename the column names in the table but I cannot modify it

**Comment by lucadelu** [comment]
I also have `AttributeError: 'numpy.int64' object has no attribute 'to_pydatetime'` error when I run get_start_time or get_end_time.
It seems to me that `traj.df.index` return the index number and min() is returning the first index, I have the t column 

```
AttributeError                            Traceback (most recent call last)
<ipython-input-23-233768a2683f> in <module>
----> 1 traj.get_start_time()

~/gitfem/euromammals/venv/lib/python3.9/site-packages/movingpandas-0.7rc1-py3.9.egg/movingpandas/trajectory.py in get_start_time(self)
    356             Trajectory start time
    357         """
--> 358         return self.df.index.min().to_datetime()
    359 
    360     def get_end_time(self):

AttributeError: 'numpy.int64' object has no attribute 'to_pydatetime'
```

**Comment by anitagraser** [comment]
Ah "It seems to work but then I get two geomemetry fields, geom and geometry" ... so gpd.GeoDataFrame.from_postgis() does some weird things.

**Comment by anitagraser** [comment]
> I have the t column

Great! Now just set the index of the GeoDataFrame

```animal_df.set_index('t', inplace=True)```

**Comment by anitagraser** [comment]
>Probably I should rename the column names in the table but I cannot modify it 

The GeoDataFrame geometry column can be renamed:

```animal_df.rename(columns={'geom':'geometry'}, inplace=True)```

**Comment by anitagraser** [comment]
@lucadelu did you get it to work now?

**Comment by lucadelu** [comment]
@anitagraser yes, renaming geom column and set t as index works!

Thanks a lot

**Comment by lucadelu** [comment]
Renaming geom in geometry brakes geodataframe in Trajectory and  hvplot doesn't work any more (but get_bbox work properly).
Applying your patch everything works fine (just to rename index, but now a error message appear and it help a lot)

**Comment by anitagraser** [comment]
Ok, please open a new ticket if you encounter any more issues with the development version.
