### ISSUE TITLE
Plotting parts of a trajectory collection

### ISSUE THREAD

**Issue by oskarwiese** [anitagraser/movingpandas#122]
Hey,

Is it possible to plot only part of a trajectory collection? I.e. a TrajectoryCollection with 1796 trajectories, where I might want to see 100 of these in a hvplot. I've concluded that it is possible to plot one trajectory by assessing the individual trajectories. However, I cannot figure out how to plot multiple trajectories without plotting the whole collection.

**Comment by oskarwiese** [comment]
I found a solution:

def make_trajectories(length, collection):
    from movingpandas import TrajectoryCollection
    test = []
    for i in range(length):
        traj = collection.trajectories[i]
        test.append(traj)
    return TrajectoryCollection(test, min_length=100)

**Comment by anitagraser** [comment]
Hi Oskoar,

The quickest approach is:

`tc2 = mpd.TrajectoryCollection(traj_collection.trajectories[:2])`

e.g.

![image](https://user-images.githubusercontent.com/590385/122930062-ec0a6e00-d36b-11eb-9921-d4c774a7d858.png)
