### ISSUE TITLE
Implement HomeRangeCalculator class

### ISSUE THREAD

**Issue by lucadelu** [anitagraser/movingpandas#126]
Could be useful to add function to return home range polygons like MCP or kernel-density.

For MCP it is quiet simple because GeoDataframe.geom.unary_union.convex_hull should be enough.
For kernel-density instead I calculated it using scipy, so this should be a new dependencies.

Let me know if make sense to have these functions inside MovingPandas

**Comment by anitagraser** [comment]
Dear Luca, yes, I think this would be a good fit for MovingPandas. Let's start with the simple MCP and take it from there. I'm looking forward to your PR.

**Comment by anitagraser** [comment]
Thank you for the PR @lucadelu! 

Eventually, I think this should be refactored into a dedicated class, e.g. HomeRangeCalculator similar to TrajectoryGeneralizer  https://github.com/anitagraser/movingpandas/blob/master/movingpandas/trajectory_generalizer.py

**Comment by lucadelu** [comment]
Yes if we add more home range methods could make sense.

**Comment by anitagraser** [comment]
Closing for lack of feedback. Will reopen on request.
