### ISSUE TITLE
Movingpandas for non-geo data?

### ISSUE THREAD

**Issue by edgarbc** [anitagraser/movingpandas#127]
Hi there,

I am trying to plot trajectories (of mice) using python and I found this great library (watched a couple of tutorials on youtube). I am wondering if I could use it on a different reference system (a mouse home cage) other than geo maps since I would like to do operations that this library already does, segment analysis, operations with ROIs, speed, interpolation, trajectory aggregation, etc.

I apologize if this question is out of place, I have no experience on GIS data.

THanks!
Edgar

**Comment by anitagraser** [comment]
Hi Edgar, the use case you describe is something I'd like to support with MovingPandas. So far, I haven't done extensive testing on the current limitations and potentially necessary improvements. Would you be able to share a mouse dataset and a few analysis examples that are relevant to your research? That would be extremely helpful to evaluate the suitability of MovingPandas and to develop a corresponding demo showcase.

**Comment by edgarbc** [comment]
Great! I am happy to share data and analysis. This would be a fantastic tool. I am also happy to contribute into the development.

**Comment by anitagraser** [comment]
You can use any file sharing you want to provide the most sample dataset. Eventually, I'd like to include it into the MovingPandas examples repo.

**Comment by anitagraser** [comment]
Closing for lack of feedback.
