### ISSUE TITLE
Port trajectory compression from MovinPy

### ISSUE THREAD

**Issue by anitagraser** [anitagraser/movingpandas#128]
In collaboration with https://github.com/giorgostheo 

https://github.com/DataStories-UniPi/MovinPy/blob/master/traj_compression.py

**Comment by anitagraser** [comment]
@giorgostheo could the compression be implemented as another TrajectoryGeneralizer?  https://github.com/anitagraser/movingpandas/blob/master/movingpandas/trajectory_generalizer.py

**Comment by giorgostheo** [comment]
Yeah that shouldn't be a problem.

**Comment by anitagraser** [comment]
And we have a successful merge. Thank you @giorgostheo !

**Comment by kntrdzs** [comment]
Unlike the other Generalizer functions the TopDownTimeRatioGeneralizer gives an error (AttributeError: 'Series' object has no attribute 'geometry'.) No matter that i use a trajectory or trajectorycollection.

**Comment by anitagraser** [comment]
@kntrdzs Please open a new ticket and include code and sample data to reproduce the issue. Thank you.
