### ISSUE TITLE
formatting and linting?

### ISSUE THREAD

**Issue by raybellwaves** [anitagraser/movingpandas#143]
Could apply tools such as black and flake8 on the repo. This can then be added to as a hooks before a commit is made e.g. https://github.com/geopandas/geopandas/blob/master/.pre-commit-config.yaml. Can also have checks on PRs.

More info: https://docs.geopandas.org/en/latest/community/contributing.html#style-guide-linting

**Comment by anitagraser** [comment]
Hi Ray, I think this is a good idea. Is it enough to just create the yaml file you linked?

**Comment by raybellwaves** [comment]
> Hi Ray, I think this is a good idea. Is it enough to just create the yaml file you linked?

Couple of things which can be separate PR's:
 - [ ] add formatting and linting deps to https://github.com/anitagraser/movingpandas/blob/master/environment.yml
 - [ ] Add the .pre-commit-config.yaml
 - [ ] could switch out travis CI for GitHub actions. E.g. geopandas has linting step/check in their GHA: https://github.com/geopandas/geopandas/blob/master/.github/workflows/tests.yaml (https://github.com/geopandas/geopandas/blob/master/.github/workflows/tests.yaml#L16)
 - [ ] Separate PR for running black/flake8 on the repo. This diff will probably be huge so probably want to do last

**Comment by anitagraser** [comment]
Looks like #163 deactivated Travis and Codecov integration. Would be good to get the tests up an running again soon.

**Comment by raybellwaves** [comment]
Hmm. Maybe GHA ran that over Trvis CI. I'll make a PR after lunch to add the tests. It'll fail as lintiing current fails but hopefully i'll fix linting and formatting tomorrow

**Comment by anitagraser** [comment]
Looks like all is in place and we're ready for black/flake8?

**Comment by raybellwaves** [comment]
Thanks for the mammoth work here @anitagraser ! Looks like GitHub CI is all green so closing.

**Comment by anitagraser** [comment]
Thanks for starting this initiative, @raybellwaves ! It's great to know that MovingPandas is now following proper code standards and that we got rid of the external Travis dependency. Time will tell how easy the GHAs are to maintain :)
