### ISSUE TITLE
Broken docs build

### ISSUE THREAD

**Issue by anitagraser** [anitagraser/movingpandas#145]
Log: https://readthedocs.org/api/v2/build/15140261.txt

It's an upstream issue: https://github.com/sphinx-doc/sphinx/issues/9727

**Comment by anitagraser** [comment]
Still broken

**Comment by anitagraser** [comment]
https://github.com/readthedocs/readthedocs.org/issues/8616

**Comment by ThiefMaster** [comment]
@anitagraser You may want to remove the link to the fake github site in your issue and replace it with the real one. Seems to be phishing, and they had better SEO than the real github during the weekend when searching for this sphinx error.

**Comment by anitagraser** [comment]
https://github.com/anitagraser/movingpandas/pull/154
