### ISSUE TITLE
filter trajectory collection based on duration

### ISSUE THREAD

**Issue by raybellwaves** [anitagraser/movingpandas#147]
I have a trajectory collection. I would like to keep the trajectories that have a duration (time at end location minus time at start location) greater than X. Is there a way to do that in movingpandas?

For example I would like to keep trajectories that last longer than three minutes. In the example below the expected outcome would be a collection of one trajectory (trajectory_id 2).

```
from shapely.geometry import Point
import geopandas as gpd
import movingpandas as mpd
import pandas as pd


df = pd.DataFrame(
    {
        "t": pd.date_range("2020-01-01", periods=5, freq="min"),
        "trajectory_id": [1, 1, 2, 2, 2],
        "geometry": [Point(0, 0), Point(0, 1), Point(0, 2), Point(0, 3), Point(0, 4)],
    }
)
gdf = gpd.GeoDataFrame(df, crs=31256)
trajc = mpd.TrajectoryCollection(gdf, traj_id_col='trajectory_id', t='t')
```

**Comment by anitagraser** [comment]
So far, the TrajectoryCollection constructor only has a min_length parameter https://movingpandas.readthedocs.io/en/master/trajectorycollection.html but you are right that a min_duration parameter would make sense as well.

**Comment by anitagraser** [comment]
```
min_duration = timedelta(minutes=1)
trajc.trajectories = [traj for traj in trajc if traj.get_duration() > min_duration]
trajc
```
![image](https://user-images.githubusercontent.com/590385/139917748-e43dc5b4-64f3-44ba-a225-525761459d72.png)

**Comment by raybellwaves** [comment]
Thanks for the work around. Closing then and continue to the convo in https://github.com/anitagraser/movingpandas/issues/148
