### ISSUE TITLE
MinSpeedSplitter

### ISSUE THREAD

**Issue by raybellwaves** [anitagraser/movingpandas#149]
In doing https://github.com/anitagraser/movingpandas/issues/142 I realized i'm interesting in a MinSpeedSplitter.

I imagine this is similar to https://movingpandas.readthedocs.io/en/master/trajectorysplitter.html#movingpandas.SpeedSplitter
however, doesn't require a duration parameter. Just a min_speed parameter (and possibly a speed_col_name).

I understand this may not conform with trajectory analysis.

In the following example I'm only interesting in splitting where speed is less than 2 m/s. There's probably some nuances on trajectory start and end but I would like minute 2-3 to be the first trajectory and minute 5-6 to be the second

```
import geopandas as gpd
import movingpandas as mpd
import pandas as pd
from shapely.geometry import Point

df = pd.DataFrame(
    {
        "t": pd.date_range("2020-01-01", periods=7, freq="s"),
        "geometry": [
            Point(0, 0),
            Point(0, 1),
            Point(0, 3),
            Point(0, 5),
            Point(0, 6),
            Point(0, 8),
            Point(0, 10),
        ],
    }
).set_index("t")
gdf = gpd.GeoDataFrame(df, crs=31256)
traj = mpd.Trajectory(gdf, 1)
traj.add_speed()
traj.df
```

![Screen Shot 2021-11-02 at 5 20 57 PM](https://user-images.githubusercontent.com/17162724/139953471-8125aaf7-b22f-454c-9c52-9220fa6ebf78.png)

I have (some horrible) pandas workaround to demonstrate expected but I think movingpandas can do this.

```
# Run example above first
gdf = traj.df
min_speed = 1
gdf[f"speed_gt_{min_speed}"] = gdf["speed"] > min_speed

gdf["traj_id"] = -1

traj_id = 0
last_value = True
for row in gdf.itertuples():
    index = row.Index
    value = row.speed_gt_1
    if value:
        if not last_value:
            traj_id += 1
            gdf.loc[index, "traj_id"] = traj_id
        else:
            gdf.loc[index, "traj_id"] = traj_id
        last_value = True
    else:
        last_value = False
```

![Screen Shot 2021-11-02 at 5 35 18 PM](https://user-images.githubusercontent.com/17162724/139955076-76ad6a0e-ed1b-4a71-84fb-d6f1b9063574.png)

**Comment by anitagraser** [comment]
You effectively get this behavior, if you use a duration of 1 second:

![image](https://user-images.githubusercontent.com/590385/140646487-f968e14b-9e0d-4b72-93df-623648a78baa.png)

I'm not sure it's worth implementing another class for this.

**Comment by raybellwaves** [comment]
ah thanks. I believe I was confused in what to add to `duration`.
