### ISSUE TITLE
Implement Kalman filter

### ISSUE THREAD

**Issue by anitagraser** [anitagraser/movingpandas#15]
Potential starting points: https://stackoverflow.com/a/51265193/449624 and https://www.youtube.com/watch?v=9Q8nEA_0ccg

**Comment by simonrmaskell** [comment]
There's another project, Stone Soup (https://github.com/dstl/Stone-Soup) which aims to provide an open-source repo of "tracking" algorithms (including, but far from limited to, Kalman filters) and has recently been improved to make use of geospatial data structures similar to those that I think are part of movingpandas. Can you specify where any Kalman filter or related algorithms would sensibly sit and/or what the input/outputs would sensibly be?

**Comment by anitagraser** [comment]
Thank you for the pointer to Stone soup, Simon! The main reason for adding a Kalman filter is as a way to remove outliers from (or smooth jittery) GPS trajectories, It would be conceptually similar to the already existing TrajectoryGeneralizers: input is the raw trajectory, output is the cleaned trajectory.

**Comment by simonrmaskell** [comment]
Am i right to think that the outliers are uninformative? If the task is outlier removal for each sequence of reports, we probably want something a little more sophisticated than a kalman filter (eg an IMM, which is also in Stone Soup already). If we want to use other information to help (eg we know the trajectories are on a known road network), we could opt for something more sophisticated still (eg a particle filter). Are there specific use cases or example test data that exemplify the issue?

**Comment by anitagraser** [comment]
So far, MovingPandas deals with unconstrained movement data (i.e. not network-constrained) so I'd prefer to start with methods that don't require additional data beyond the movement itself. I haven't compiled any test data for this usecase yet. Does Stone soup include some that we could use?

**Comment by anitagraser** [comment]
In the Geolife sample, we can find quite some noise: https://mybinder.org/v2/gh/anitagraser/movingpandas/binder-tag?filepath=tutorials/tutorial_getting_started.ipynb
![image](https://user-images.githubusercontent.com/590385/95011236-a1a35e80-062f-11eb-91aa-a65835dffaf9.png)

**Comment by simonrmaskell** [comment]
I was going to look up a dataset we played with a while back and you just reminded me that it was called geolife. That's certainly something we can start with.

Constraints can be soft but starting with none seems like a plan. We'll take a look and do things in a way where upgrading to more sophisticated algorithms will be easy later.
