### ISSUE TITLE
Trajectory.get_linestring_between() needs more parameters to use Trajectory._make_line()

### ISSUE THREAD

**Issue by parnelandr** [anitagraser/movingpandas#16]
The Trajectory.get_linestring_between() method asks for two datetime objects as parameters and tries the Trajectory._make_line() method with the Trajectory.get_segment_between() method.

However, Trajectory._make_line() is expecting a DataFrame that has a length but is receiving a trajectory.Trajectory object that doesn't have a length from the Trajectory.get_segment_between() method.

The error received is - TypeError: object of type 'Trajectory' has no len()

**Comment by anitagraser** [comment]
Thank you for reporting! It should be fixed now and a corresponding test has been added.
