### ISSUE TITLE
Add trajectory ID to TrajectoryCollection.to_point_gdf() export

### ISSUE THREAD

**Issue by raybellwaves** [anitagraser/movingpandas#162]
I would like to export a TrajectoryCollection to the original gdf but will an addition column of `trajectory_id` (named `id` by default in moving pandas) (i.e. this is what you see with `trajc.to_traj_gdf()`.

I can get the points back using `.to_point_gdf` but you lose the trajectory information (i.e. that is given in `.to_traj_gdf()`.

For example see https://github.com/anitagraser/movingpandas-examples/blob/main/1-tutorials/6-splitting-trajectories.ipynb

after

```
split = mpd.ObservationGapSplitter(my_traj).split(gap=timedelta(minutes=2))
```
doing
```
split.to_point_gdf()
```
shows the input:

<img width="671" alt="Screen Shot 2021-12-12 at 10 18 20 PM" src="https://user-images.githubusercontent.com/17162724/145747096-2db69a81-1c30-43c4-8ab5-9184ec0b38e0.png">

It would be nice to return ad extra column with the "new" trajectory id e.g. 2_0, 2_1 (obviously check for name clashes)

<img width="708" alt="Screen Shot 2021-12-12 at 10 19 12 PM" src="https://user-images.githubusercontent.com/17162724/145747210-358e74e2-178d-4608-886e-1522b6294ddb.png">

This is mostly because I work with data without a trajectory_id so it would be nice to return one.

**Comment by anitagraser** [comment]
Great point. I've run into this issue as well. I think I'll call the parameter `with_traj_id` and let it default to True.

**Comment by anitagraser** [comment]
I've thought some more about it and I think the most flexible and consistent implementation is to provide an .add_traj_id(overwrite=False) function that can be called any time (not just when exporting to point gdf).

**Comment by raybellwaves** [comment]
> I've thought some more about it and I think the most flexible and consistent implementation is to provide an .add_traj_id(overwrite=False) function that can be called any time (not just when exporting to point gdf).

Sounds good. Would match over attributes e.g. `.add_speed()`
