### ISSUE TITLE
Intersection between trajectories of the same TrajectoryCollection

### ISSUE THREAD

**Issue by catarina-nunes** [anitagraser/movingpandas#179]
I converted the TrajectoryCollection to gdf, both through to_line_gdf and to_traj_gdf, and I would like to know which trajectories intersect each other within the same geodataframe, but I'm not able to. Is there any recommended way?
Thank you in advance for any contribution that can be made.

**Comment by anitagraser** [comment]
Are you interested in spatiotemporal closest point of approach (#31) or pure geometric intersection?

**Comment by catarina-nunes** [comment]
> Are you interested in spatiotemporal closest point of approach (#31) or pure geometric intersection?

I believe that a spatiotemporal closest point of approach is the most appropriate, yes. I need to know which trajectories are less than 400 meters from each other, in the time period of 2 hours. Is this possible?

**Comment by anitagraser** [comment]
Unfortunately CPA computation is not implemented yet. PostGIS already has CPA functions in case you are familiar with it.

**Comment by catarina-nunes** [comment]
OK thank you! I will try to explore! Do you recommend any specific documentation?

**Comment by anitagraser** [comment]
https://postgis.net/docs/ST_CPAWithin.html sounds perfect for your requirements.

**Comment by anitagraser** [comment]
I'm closing this ticket in favor of the existing #31
