### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by Robinlovelace** [anitagraser/movingpandas#180]
I'm pretty new to the world of Python but just hit this issue so thought it worth reporting. Likely I'm doing something wrong though!

```bash
pip3 install geopandas movingpandas rasterio rioxarray jupyter
```

Ends in this error message on my desktop:

```
ERROR: movingpandas 0.9rc2 has requirement shapely<1.8, but you'll have shapely 1.8.0 which is incompatible.
Installing collected packages: pillow, bokeh, pyshp, cartopy, geographiclib, geopy, param, pyct, colorcet, pyviz-comms, panel, holoviews, geoviews, hvplot, movingpandas
Successfully installed bokeh-2.4.2 cartopy-0.20.2 colorcet-3.0.0 geographiclib-1.52 geopy-2.2.0 geoviews-1.9.3 holoviews-1.14.7 hvplot-0.7.3 movingpandas-0.9rc2 panel-0.12.6 param-1.12.0 pillow-9.0.0 pyct-0.4.8 pyshp-2.1.3 pyviz-comms-2.1.0
```

Issue first spotted on reproducible docker build: https://github.com/geocompr/docker/runs/5008434217?check_suite_focus=true#step:8:715

**Comment by anitagraser** [comment]
Hi @Robinlovelace, good to hear from you. Any chance you can use conda? Pip isn't really supported by MovingPandas, as described in https://github.com/anitagraser/movingpandas#installation

**Comment by Robinlovelace** [comment]
Yes good chance I can... Need to figure out how to get it all working in Docker. Recalling discussions of pip vs conda vs poetry on other threads. However, is it right that movingpandas depends on an earlier (<1.8) version of shapely (guess I can check the yml files for that, will do ; )

**Comment by Robinlovelace** [comment]
Confirmed: https://github.com/anitagraser/movingpandas/blob/master/environment.yml#L25 I think one of the packages required for another project I'm working on `rasterio` ? @michaeldorman probably knows better, needs a higher version, meaning it's hard to have the 2 pkgs in the same environment, unless `conda` can sort that...

**Comment by Robinlovelace** [comment]
Minor update, trying with

```
conda install -c conda-forge movingpandas geopandas rasterio rioxarray jupyter
``` 

So far so good...

**Comment by Robinlovelace** [comment]
Update, I get this:

```
conda install -c conda-forge movingpandas geopandas rasterio rioxarray jupyter  
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
```

Not sure if this is reproducible on other computers.

**Comment by anitagraser** [comment]
We had to [pin shapely](https://github.com/anitagraser/movingpandas/commit/42a9203c74dc229893862949ca3c62f19d42bb59) because Geoviews 1.9.2 was not yet compatible with shapely-1.8.0. 
This should be fixed, according to https://github.com/holoviz/geoviews/releases. So we can remove the pin again.
