### ISSUE TITLE
Issues using TrajectoryCollection on my csv dataframe.

### ISSUE THREAD

**Issue by Jharkins123** [anitagraser/movingpandas#185]
Hi,

I have been following the tutorials with no issues, however, after finishing them all, I have tried to use hvplot to plot the TrajectoryCollection made from my dataframe, however I found that it was not returning any sort of graph:
![image](https://user-images.githubusercontent.com/82601052/153915103-e92049f4-0786-4b3f-a2c4-d10d09544f27.png)
Using len(traj_collection) shows it has a length of 0, so no trajectories are being made for some reason but I am not sure why, I have followed exactly as is shown in the tutorials?

Thanks,
Jacob

**Comment by Jharkins123** [comment]
I also seem to get this error in the console:
IPKernelApp No such comm: hv-extension-comm
Looking online, it seems that this error is harmless, so it is likely not relevant.

**Comment by anitagraser** [comment]
Hi Jacob, please share a few lines of your csv, so I can attempt to reproduce the issue.

**Comment by Jharkins123** [comment]
> 
Hi,
![image](https://user-images.githubusercontent.com/82601052/153918069-6a70b904-2c18-43e2-9bb7-76ce76a424e7.png)
Thanks a lot for the help regardless,
Jacob

**Comment by anitagraser** [comment]
LocalTime is just a timestamp, you need to take care to first create a column with datetimes, combining both date and time.

**Comment by Jharkins123** [comment]
> LocalTime is just a timestamp, you need to take care to first create a column with datetimes, combining both date and time.

Okay, I'll give it a try, thanks for the help.

**Comment by Jharkins123** [comment]
![image](https://user-images.githubusercontent.com/82601052/153920202-2acfc29c-0b02-44ae-b0c2-fc9edb1765b7.png)
Like so ? I am still getting no trajectories it seems.

**Comment by anitagraser** [comment]
If you post the data and code as text, I can give it a try.

**Comment by anitagraser** [comment]
The ID of row 1 is different than row 0. Are there more positions with the same object ID later on? Trajectories with one point only will be silently discarded.

**Comment by Jharkins123** [comment]
No, they all have unique objectID's, if that is the case then that may be the issue I am having.

**Comment by Jharkins123** [comment]
I'll have to get permission from my university to share the data, is it fine to email you ?

**Comment by anitagraser** [comment]
No need. It's certainly the ID issue.

**Comment by anitagraser** [comment]
Have you been able to figure it out? Can we close this issue?

**Comment by Jharkins123** [comment]
Yes, that was the issue, thanks for the help, appreciate it!
