### ISSUE TITLE
open discussion tab on github page

### ISSUE THREAD

**Issue by raybellwaves** [anitagraser/movingpandas#193]
https://docs.github.com/en/discussions

Can move user questions there e.g. https://github.com/anitagraser/movingpandas/issues/192

**Comment by raybellwaves** [comment]
Not sure. May have to do by hand. Good also make a notebook of it in the ISSUE template which people will see when creating an issue

**Comment by anitagraser** [comment]
Found the button 
![image](https://user-images.githubusercontent.com/590385/156922452-966ea9fe-e953-4c06-baee-94e4896e907e.png)
