### ISSUE TITLE
BUG: MovingPandas won't install using conda-forge

### ISSUE THREAD

**Issue by Rory-RMJ** [anitagraser/movingpandas#214]
If you have a question, rather than a bug report, please post in the [discussions](https://github.com/anitagraser/movingpandas/discussions).
Otherwise, please check: 

- [x ] I have checked that this issue has not already been reported.

- [x ] I have confirmed this bug exists on the latest version of MovingPandas.

- [x ] (optional) I have confirmed this bug exists on the main branch of MovingPandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Problem description
Installing movingpandas using `conda install -c conda-forge movingpandas` - yet when I go to import the library, it won't import in my IDE. I have also checked `conda list` and it isn't there so I don't think it installs. After the install command is run it ends with a lot of conflicts. 

#### Output of one of the conflicts in the terminal`
An example of one of the (very many) conflicts 

`Package jupyter_console conflicts for:
anaconda==2021.11 -> jupyter==1.0.0=py39haa95532_7 -> jupyter_console
anaconda==2021.11 -> jupyter_console==6.4.0=pyhd3eb1b0_0
jupyter -> jupyter_console`

**Comment by anitagraser** [comment]
Please test with a new Python environment. It looks like the current environment contains conflicting installations, potentially from other channls than conda-forge (cannot tell without the full list).

To install a working environment, you can use this environment file: 
https://github.com/anitagraser/movingpandas-examples/blob/main/environment.yml  
That's the one we use to build MovingPandas demos on MyBinder:  https://mybinder.org/v2/gh/anitagraser/movingpandas-examples/main 

![image](https://user-images.githubusercontent.com/590385/159987219-19d22f91-6235-4b94-9a6f-e05517ea7954.png)

**Comment by Rory-RMJ** [comment]
All working now, thanks!
