### ISSUE TITLE
ENH: silence missing Missing optional dependencies on import

### ISSUE THREAD

**Issue by raybellwaves** [anitagraser/movingpandas#220]
Currently if a user installs moving pandas as runs

`import movingpandas as mpd` they will see "INFO: Missing optional dependencies. To use the trajectory smoother classes please install Stone Soup (see https://stonesoup.readthedocs.io/en/latest/#installation)."

I feel this adds noise if someone is not interested in the smoother classes.

I wonder is there is a way to only raise this if a user tries to do `mpd.KalmanSmootherCV(traj)`.

I know i've had the opposite problem where I wanted to use `KalmanSmootherCV` and "INFO: Missing optional dependencies" was not raised. So not sure if it is possible.

**Comment by anitagraser** [comment]
That's fixed in https://github.com/anitagraser/movingpandas/commit/2d38779b038c3410e2527df2de44c7e00c7ddcc7, right?
