### ISSUE TITLE
rename master branch to main branch

### ISSUE THREAD

**Issue by raybellwaves** [anitagraser/movingpandas#222]
https://github.com/github/renaming#renaming-existing-branches

**Comment by anitagraser** [comment]
Done. You'll need to update your local environment: 

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

**Comment by anitagraser** [comment]
@raybellwaves do you know if `pypa/gh-action-pypi-publish@master` has to be changed to `pypa/gh-action-pypi-publish@main` in https://github.com/anitagraser/movingpandas/blob/main/.github/workflows/release_to_pypi.yml?
