### ISSUE TITLE
Return more representative stop point

### ISSUE THREAD

**Issue by anitagraser** [anitagraser/movingpandas#231]
Currently, the stop point geometry is the stop segment start location:

https://github.com/anitagraser/movingpandas/blob/660aa3b5ddaa5b2554eba2a473e0fdbc491f18ba/movingpandas/trajectory_stop_detector.py#L174-L178

this should be replaced by a more representative point. 

For comparison: scikit-mobility calculates the median lat/lon of all positions in the stop segment:

https://github.com/scikit-mobility/scikit-mobility/blob/023918e499070a32406a1e909f596a5a19b881a5/skmob/preprocessing/detection.py#L199

**Comment by anitagraser** [comment]
```
seg = # stop segment
pt = Point(seg.df.geometry.x.median(), seg.df.geometry.y.median())
```

**Comment by radical-squared** [comment]
Wouldn't a centroid over the stop points be more representative? Using geopandas' unary_union, it should be very easy to implement. 

trajectory.py:
```   
 def get_centroid(self):
        """
        Return the trajectory's centroid point.

        Returns
        -------
        shapely Point
            Trajectory centroid point
        """
        return self.df.geometry.unary_union.centroid
```

trajectory_stop_detector.py:

```
        for stop in stops:
            stop_pts.at[stop.id, "start_time"] = stop.get_start_time()
            stop_pts.at[stop.id, "end_time"] = stop.get_end_time()
            #stop_pts.at[stop.id, "geometry"] = stop.get_start_location()
            stop_pts.at[stop.id, "geometry"] = stop.get_centroid()
            stop_pts.at[stop.id, "traj_id"] = stop.parent.id
```

**Comment by anitagraser** [comment]
I considered it but the centroid would be more sensitive to outliers such as erroneous gps spikes.

**Comment by radical-squared** [comment]
Fair point. Median is immune to outliers. Thanks for clarifying that to me.
