### ISSUE TITLE
Typo in mrr_diagonal 

### ISSUE THREAD

**Issue by snelmes** [anitagraser/movingpandas#249]
Thank you so much for your great package, it's so useful.

I believe line 156 in  mrr_diagonal in geometry_utils.py 
``return _measure_distance(Point(mrr.coords[0]), Point(mrr.coords[-1], spherical))``
has its brackets incorrectly placed and should be
``return _measure_distance(Point(mrr.coords[0]), Point(mrr.coords[-1]), spherical)``
so that the ``spherical`` is outside of the second ``Point`` bracket. Without this change, whether ``spherical`` is true or false is ignored in the ``_measure_distance`` function and is set to the default of false. In my case, this resulted in the stop detector giving incorrect start and end times of stops. 

<details>

MovingPandas 0.11.rc1

SYSTEM INFO
-----------
python     : 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:59:51)  [GCC 9.4.0]
executable : /home/susan/miniconda3/envs/ds-gridding/bin/python
machine    : Linux-5.4.0-1088-aws-x86_64-with-glibc2.10

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.10.1
GEOS lib   : /home/susan/miniconda3/envs/ds-gridding/lib/libgeos_c.so
GDAL       : 3.3.3
GDAL data dir: /home/susan/miniconda3/envs/ds-gridding/share/gdal
PROJ       : 8.2.0
PROJ data dir: /home/susan/miniconda3/envs/ds-gridding/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.10.2
pandas     : 1.3.4
fiona      : 1.8.20
numpy      : 1.21.3
shapely    : 1.8.0
rtree      : 0.9.7
pyproj     : 3.3.0
matplotlib : 3.3.2
mapclassify: 2.4.3
geopy      : 2.2.0
holoviews  : 1.14.6
hvplot     : 0.7.3
geoviews   : 1.9.3
stonesoup  : None

</details>

**Comment by anitagraser** [comment]
Excellent catch, Susan. You are welcome to submit a PR addressing this issue, ideally including corresponding unit tests, if you want.

**Comment by snelmes** [comment]
Thanks. I've submitted a PR.

**Comment by snelmes** [comment]
I've added a unit test to my PR
