### ISSUE TITLE
Should functions clean up temporary df columns?

### ISSUE THREAD

**Issue by anitagraser** [anitagraser/movingpandas#25]
Currently, functions such as `__str__()` and `plot()` add columns to the Trajectory.df. Should functions have to clean up after themselves? Or is it better to keep these columns once they have been calculated to avoid having to recompute them again and again?

**Comment by rlukevie** [comment]
I think, the columns shouldn't be left in the main dataframe. A user won't expect new columns after calling `__str__()` or `plot()`. 

Maybe store the columns in additional dataframes, calculate a hash on the input columns and function arguments (if any), store it too, and compare the hash to decide if recomputation is needed. I'm not sure, how big the performance gain could be, but it could be worth a try. Some proper profiling would be necessary to decide on this, I guess.
