### ISSUE TITLE
traj_collection.to_line_gdf() removes some observations

### ISSUE THREAD

**Issue by lorenzlorg** [anitagraser/movingpandas#278]
I've a dataset of 965931 rows (points) and grouping by traj_id I have 1489 trajectories. 

Then I've used:
`traj_collection = mpd.TrajectoryCollection(df_geopandas_long_traj_mp, 'id', min_length=0, crs = 'epsg:32632')
`

where `df_geopandas_long_traj_mp ` is the dataset mentioned before.

Using `traj_collection.to_line_gdf()` I get the correct number of trajectories, 1489, but a smaller number of points (964442).

I've noticed that considering 965931 - 964442 i get the number of trajectories.

How does it work? Why are there missing points?

**UPDATE:**
I've discovered that it discards the first frame of each trajectory and I don't understand why.

It seems that `to_line_gdf()` has problems. Is it possible that it skips the first row?

**Comment by lorenzlorg** [comment]
I've discovered that it discards the first frame of each trajectory and I don't understand why

**Comment by anitagraser** [comment]
Dear Lorenzo,
Imagine a toy trajectory with n=3 points. When we connect consecutive points, we get n-1=2 lines.
to_line_gdf() creates lines.
to_point_gdf() returns the points.
Hope this helps.
