### ISSUE TITLE
Test libraries for interactive visualizations

### ISSUE THREAD

**Issue by anitagraser** [anitagraser/movingpandas#35]
Spatial support is now implemented https://github.com/altair-viz/altair/pull/1664

**Comment by slothkong** [comment]
From all tasks this seems to be the one that requires the least formal knowledge of both all the theory and the code base. If you were to test this where would you start? First time I come across [altair](https://github.com/altair-viz/altair). Seems quite useful.

**Comment by anitagraser** [comment]
Thank you for your interest in taking over this task @slothkong !

The main advantage I'm hoping for is to have interactive plots. For example, the current Trajectory.plot() function can show speed along the trajectory using different colors and we can add a legend to explain the colors but with Altair, I would hope that the user can hover over a line segment and see the actual speed value.

**Comment by slothkong** [comment]
ok. I can l play  a bit with [0_getting_started.ipynb](https://github.com/anitagraser/movingpandas/blob/master/tutorials/0_getting_started.ipynb) and see if I can plot the same data with the new lib.
Just out of curiosity, have you considered [plotly](https://plot.ly/python/#statistical-charts)?
I think this kind of interactivity you hope to achieve could also be easily implemented on it, with the benefit that is a more standard library, getting tons of love by the dev community these days. Might give `MovingPandas` an extra boost and ease up open source developement

**Comment by anitagraser** [comment]
Plotly would be a great addition as well and it would most likely be a more sensible first step. I'll open a separate ticket for plotly.

Altair get's really powerful when used to create linked charts but I might be getting ahead of myself.

**Comment by anitagraser** [comment]
@slothkong looking forward to seeing what you come up with

**Comment by anitagraser** [comment]
I've started an ipynb comparing folium and hvplot:

![image](https://user-images.githubusercontent.com/590385/68525866-57f2ac80-02d6-11ea-8c29-817c74308948.png)

https://github.com/anitagraser/movingpandas/blob/master/tutorials/3_interactive_maps.ipynb

**Comment by anitagraser** [comment]
Going forward with hvplot https://github.com/anitagraser/movingpandas/commit/1df39ceced0cf08539dca56490a4fafce8653d95
