### ISSUE TITLE
Making a conda-forge package?

### ISSUE THREAD

**Issue by jorisvandenbossche** [anitagraser/movingpandas#36]
I saw on twitter you released on PyPI (congrats!), so was thinking it would be good to have a conda-forge package so people can install it more easily with the rest of the geospatial stack provided by conda-forge?

For a pure python package, it is relatively easy to add a package (creating a PR at https://github.com/conda-forge/staged-recipes/). But gladly to help with that if you have any problems.

**Comment by anitagraser** [comment]
Thanks Joris! I've created a conda package for Win64 yesterday: https://anaconda.org/anitagraser/movingpandas
As you can see, it's not on conda-forge yet. Any help with that would be greatly appreciated.

**Comment by jorisvandenbossche** [comment]
@anitagraser I created a PR to add a feedstock for movingpandas to conda-forge. Once that is merged, this should ensure that a conda-forge package is built for all platforms. 

When doing new releases, you need to update the feedstock there as well. But, if you do a release on PyPI, there is a bot that will automatically create a PR on that feedstock to update it, so normally the only you need to do is merge that PR.

**Comment by jorisvandenbossche** [comment]
Packages are now available! ;) https://anaconda.org/conda-forge/movingpandas

So you can now do `conda install movingpandas -c conda-forge` on all platforms (of course with still the rasterio problem on windows)

**Comment by anitagraser** [comment]
Awesome work, thank you!
