### ISSUE TITLE
Use Geopy to compute distances

### ISSUE THREAD

**Issue by anitagraser** [anitagraser/movingpandas#4]
Shapely does not support coordinate system transformations. All operations on two or more features presume that the features exist in the same Cartesian plane.
https://shapely.readthedocs.io/en/stable/manual.html#coordinate-systems

Geopy can calculate geodesic distance between two points using the geodesic distance or the great-circle distance, with a default of the geodesic distance available as the function geopy.distance.distance.
https://geopy.readthedocs.io/en/stable/#module-geopy.distance

**Comment by git-it** [comment]
basic testing yields *geopy* is faster than *Nvector*
![image](https://user-images.githubusercontent.com/6565767/106670830-c7ebf300-656a-11eb-908b-6f611d2587a4.png)
this looks like a good starter issue. I'll give it a shot.
