### ISSUE TITLE
Does 0.1.dev2 from conda-forge include TrajectoryManager?

### ISSUE THREAD

**Issue by jonititan** [anitagraser/movingpandas#41]
Sad error here.
Clean install into dedicated environment on Windows 10.
environment.yml records version as 

movingpandas=0.1.dev2=py37h39e3cac_0

When trying to use the TrajectoryManager class from the tutorial it fails saying the module has no such attribute.

I can't see any releases on github so wondered if conda has lagged behind github?

**Comment by anitagraser** [comment]
Yes, TrajectoryManager has only recently been added and is not yet available via conda

**Comment by anitagraser** [comment]
The Notebooks in https://github.com/anitagraser/movingpandas/tree/240020788a8798b56727506b7490acbfff364f3d should work with the conda version

**Comment by djoostwoud** [comment]
Hi, does this mean that we cann't yet use our own data until TrajectoryManager is available?

**Comment by jonititan** [comment]
The only problem I had was with regard to plotting.  I was able to get it into Geopandas just fine and then convert to Movingpandas trajectory by passing a dataframe of points.  In my case it was aircraft points during a flight.  You can still use the mpd.Trajectory class

**Comment by anitagraser** [comment]
Alternatively, you can also use the development version by following the instructions in https://github.com/anitagraser/movingpandas#development-installation

**Comment by djoostwoud** [comment]
That's a very good alternative! When I load my data as a gpkg geopackage everything works just fine. However, reading a csv finally gives an error with the TrajactoryManager: 'DataFrame' object has no attribute 'crs'

**Comment by anitagraser** [comment]
For CSV, we have to specify the CRS manually, because there is no metadata section to read it from: 

```
gdf = geopandas.read_file(path_to_csv)
gdf.crs = {'init' :'epsg:4326'}
gdf.plot()
```

**Comment by djoostwoud** [comment]
Thanks. The read_file method returns max recursive errors or dead kernels, however when I first use read_csv and then convert to a geodataframe it works!
I haven't been able to get the trajectories (TimeManager objects) into qgis yet.

**Comment by anitagraser** [comment]
@djoostwoud I started a QGIS plugin that adds MovingPandas functionality to the Processing Toolbox: https://github.com/anitagraser/qgis-processing-trajectory. It should give you a general idea of how trajectories can be used in QGIS.

The plugin development is currently on ice until MovingPandas has reached at least 1.0 release status.

**Comment by anitagraser** [comment]
The new movingpandas 0.2rc1 includes TrajectoryCollection (formerly called TrajectoryManager) https://anaconda.org/conda-forge/movingpandas
