### ISSUE TITLE
'NoneType' object has no attribute 'is_ccw'

### ISSUE THREAD

**Issue by CiraciNicolo** [anitagraser/movingpandas#45]
Crashing while trying to `hvplot` a TrajectoryCollection. The DataFrame under one of the trajectory is the following:

```
geometry	trajectory_id
t		
2007-05-03 00:59:08	POINT (28.918 118.052)	0
2007-05-03 01:02:54	POINT (28.918 118.052)	0
2007-05-03 01:03:24	POINT (28.918 118.052)	0
2007-05-03 01:07:03	POINT (28.918 118.053)	0
2007-05-03 01:08:40	POINT (28.918 118.053)	0
...	...	...
2007-05-03 05:07:57	POINT (28.903 118.062)	0
2007-05-03 05:08:08	POINT (28.903 118.062)	0
2007-05-03 05:08:27	POINT (28.903 118.062)	0
2007-05-03 05:08:44	POINT (28.903 118.062)	0
2007-05-03 05:11:19	POINT (28.903 118.062)	0
```

```
~/.local/lib/python3.7/site-packages/cartopy/crs.py in _project_polygon(self, polygon, src_crs)
    352             is_ccw = True
    353         else:
--> 354             is_ccw = polygon.exterior.is_ccw
    355         # Project the polygon exterior/interior rings.
    356         # Each source ring will result in either a ring, or one or more

AttributeError: 'NoneType' object has no attribute 'is_ccw'
```

**Comment by anitagraser** [comment]
Thank you for reporting! Can you share a dataset so I can try to reproduce this issue?

**Comment by CiraciNicolo** [comment]
The dataset I'm using is GeoLife, since is a CSV I wrote a method that parse the file and returns an array of dictionary in this structure: {'geometry': aPointGeometry, t: aTimestamp, trajectory_id: anInt}.

Here you can find the bare data: https://pastebin.com/YYsWFATr
and here you can find an example of parsed data: https://pastebin.com/nQ7T9f26 and json version of it https://pastebin.com/QKMe0xE2

Here also a snippet to import the json and parse it to get the structured data:

```
import json
from datetime import datetime
from shapely.geometry import Point
a = json.loads(DATA)
a = [{'geometry': Point(x.get('geometry')[0], x.get('geometry')[1]), 't': datetime.fromtimestamp(x.get('t')), 'trajectory_id': x.get('trajectory_id')} for x in a]
```

My enviroment is jupyter lab with Python3, as far as I can see my data is almost equal to the first example provided with this packages but the outcome is different.
