### ISSUE TITLE
Hvplot: No response Kernal Die in both Jupyter Notebook and Spyder

### ISSUE THREAD

**Issue by Trafficity** [anitagraser/movingpandas#47]
I am implementing the DBSCAN on my vehicle tracking data, where after converting the all data into individual trajectories i used your DBSCAN code for clustering, but when i start running the .hvplot method it exit without showing any output (Spyder) or kernal will start automatically (Jupyter Notebook). The issue is not specific to just DBSCAN, but whenever i start using hvplot it gives me no response.Need your help in this issue. Thank you

**Comment by anitagraser** [comment]
Do the crashes only happen if MovingPandas is imported in the script? Since clustering produces a regular GeoPandas GeoDataFrame, this issue might be better suited for their issue tracker.

**Comment by anitagraser** [comment]
This issue has to be fixed upstream, see: https://github.com/Toblerity/Shapely/issues/818
