### ISSUE TITLE
CRSError is df does not have crs

### ISSUE THREAD

**Issue by martinfleis** [anitagraser/movingpandas#51]
In case of creating Trajectory from GeoDataFrame without set CRS, it fails. As you moved CRS check to init, it now fails during the creation, before it failed once `is_latlon()` was called, so no big difference. 

```py
df = pd.DataFrame([
  {'geometry':Point(0,0), 't':datetime(2018,1,1,12,0,0)},
  {'geometry':Point(6,0), 't':datetime(2018,1,1,12,6,0)},
  {'geometry':Point(6,6), 't':datetime(2018,1,1,12,10,0)},
  {'geometry':Point(9,9), 't':datetime(2018,1,1,12,15,0)}
]).set_index('t')
geo_df = GeoDataFrame(df)
toy_traj = mpd.Trajectory(geo_df, 1)
```

It might be expected behaviour not to allow Trajectory without set CRS. If so, I would check for missing CRS and raise more informative error. Alternatively you can assume lat-lon and raise a warning that this assumption is there.

Current `CRSError: Invalid CRS input: None` is quite easy to understand unlike previous `TypeError: ("'NoneType' object is not subscriptable", 'occurred at index 2018-01-01 12:06:00')`, but it could be pointing to a specific reason and a solution.

cc pyOpenSci/software-review#18

**Comment by martinfleis** [comment]
Just realised - you might have naive coordinates without CRS, so it is probably better to assume that data are projected. For example in tracking fish movement in the tank, CRS has no meaning but movingpandas is still a tool to use.

**Comment by jlpalomino** [comment]
Hi @martinfleis it looks like @anitagraser has flagged this issue as a future enhancement.  Are you comfortable with the labeling of this issue?  (It would remain as the last open issue from this review). Thanks.

**Comment by martinfleis** [comment]
@jlpalomino Yes. It is not blocking the review.

**Comment by jlpalomino** [comment]
Thank you for the prompt response @martinfleis!
