### ISSUE TITLE
TrajectoryCollection.plot ignores some kwargs

### ISSUE THREAD

**Issue by martinfleis** [anitagraser/movingpandas#52]
`TrajectoryCollection.plot()` ignores some kwargs which should be passed to `GeoDataFrame.plot()`, like `figsize`. 

While `Trajectory.plot(figsize=(12, 12))` works as expected, `TrajectoryCollection.plot(figsize=(12, 12))` ignores figsize. I am not sure what is the intention here, if all kwargs should go to gdf.plot() or just a selection, but difference in behaviour between Trajectory and TrajectoryCollection is unexpected.

cc pyOpenSci/software-review#18

**Comment by anitagraser** [comment]
I went over the logic and `TrajectoryCollection.plot` lacked the step of creating the ax with the specified figsize. However, the rest of the logic should be same as in `Trajectory.plot`.
