### ISSUE TITLE
setup of environment: dependency issues

### ISSUE THREAD

**Issue by AlexandraKapp** [anitagraser/movingpandas#60]
The bokeh update from 1.4.0 to 2.0.0 causes issues (I suppose a problem of hvplot). 
Therefore, I get an error when running the 0_getting_started.ipynb notebook.
(bokeh.plotting.helpers not found) -> was removed in 2.0.0

Manually downgrading to bokeh=1.4.0 or specifying bokeh=1.4.0 in the environment.yml fixed the issue.

**Comment by anitagraser** [comment]
Thank you for reporting Alexandra!
