### ISSUE TITLE
Change from checking with `type()` to `isinstance()`

### ISSUE THREAD

**Issue by apulverizer** [anitagraser/movingpandas#63]
I was trying to figure out why my data was not plotting or showing correct distances for trajectories. 

The issue seems to be all of the statements like:
https://github.com/anitagraser/movingpandas/blob/90b3e810a79598407954796e195e760d99c021a2/movingpandas/trajectory.py#L445

The problem is this doesn't account for when something is sub-classed. In my example the points in the geodataframe are all actually [`PointAdapter`](https://github.com/Toblerity/Shapely/blob/58073332ad85abe368cc5bc78a3b3d0d5ee5effc/shapely/geometry/point.py#L155) which is sub-classing the `Point` class. 

So in my case, the existing type checking was incorrectly flagging it as not a point. The solution is to use [isinstance](https://docs.python.org/3/library/functions.html#isinstance) method throughout the code base. 

```python
if not isinstance(pt0, Point):
    return 0.0
```

I did this in a few spots and it was working as expected.

**Comment by anitagraser** [comment]
Thanks for reporting!
