### ISSUE TITLE
TypeError: 'CRS' object is not subscriptable

### ISSUE THREAD

**Issue by paumillet** [anitagraser/movingpandas#67]
Hello,

Thanks for your developing MovingPandas, it looks promising! 
I have some trouble with CRS, because of the new syntax recommended by Pyproj for projection code. 

When I initialize a geodataframe as you present in tutorial 0, I have the following warning showing up: 
```
[...]/pyproj/crs/crs.py:55: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method.
```
Nevertheless my geodataframe is created but the CRS associated is formated given the new recommendation, not like `{'init': 'epsg:31256'}`.

Then, when I want to apply MoyingPandas functions as `add_speed()` or `.get_position_at()`, I meet the error:
```
[...]/movingpandas/trajectory.py in is_latlon(self)
    120         bool
    121         """
--> 122         if self.crs['init'] == from_epsg(4326)['init']:
    123             return True
    124         else:

TypeError: 'CRS' object is not subscriptable
```
It seems like, it's because of the CRS format, not being a dictionary with `'init'` key anymore.

Let me know if you need anything else from me to help.

Have a nice day,
Pauline

**Comment by anitagraser** [comment]
Thank you for reporting! Which version of MovingPandas are you using? This should already be fixed in v0.3

**Comment by paumillet** [comment]
```
import movingpandas as mpd
print(mpd.__version__)

0.2.rc1
```

I installed using `conda install -c conda-forge movingpandas`, how could I get v0.3?

**Comment by anitagraser** [comment]
v0.3 has been on conda-forge for 22days

**Comment by ujang-u** [comment]
I am trying to install v0.3 using pip

> `pip3.7 install movingpandas==0.3rc1`

Then facing this error:

> Collecting movingpandas==0.3rc1
>   Using cached movingpandas-0.3rc1.tar.gz (27 kB)
> Requirement already satisfied: numpy in c:\users\Ding\appdata\local\programs\python\python37\lib\site-packages (from movingpandas==0.3rc1) (1.18.2)
> Requirement already satisfied: matplotlib in c:\users\Ding\appdata\local\programs\python\python37\lib\site-packages (from movingpandas==0.3rc1) (3.2.1)Collecting shapely==1.7a3
>   Using cached Shapely-1.7a3.tar.gz (346 kB)
>     ERROR: Command errored out with exit status 1:
>      command: 'c:\users\Ding\appdata\local\programs\python\python37\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Ding\\AppData\\Local\\Temp\\pip-install-obr28pgk\\shapely\\setup.py'"'"'; __file__='"'"'C:\\Users\\Ding\\AppData\\Local\\Temp\\pip-install-obr28pgk\\shapely\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'c:\users\Ding\AppData\Local\Temp\pip-install-obr28pgk\shapely\pip-egg-info'
>          cwd: c:\users\Ding\AppData\Local\Temp\pip-install-obr28pgk\shapely\
>     Complete output (9 lines):
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "C:\Users\Ding\AppData\Local\Temp\pip-install-obr28pgk\shapely\setup.py", line 85, in <module>
>         from shapely._buildcfg import geos_version_string, geos_version, \
>       File "C:\Users\Ding\AppData\Local\Temp\pip-install-obr28pgk\shapely\shapely\_buildcfg.py", line 202, in <module>
>         lgeos = CDLL("geos_c.dll")
>       File "C:\Users\Ding\AppData\local\programs\python\python37\lib\ctypes\__init__.py", line 364, in __init__
>         self._handle = _dlopen(self._name, mode)
>     OSError: [WinError 193] %1 is not a valid Win32 application
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

It is shown that i need to use win32 application. Is there any way for Win64? I have no problem installing 0.2rc1 but again problem with `TypeError: 'CRS' object is not subscriptable`

**Comment by anitagraser** [comment]
Pip is not supported. Please see the [README](https://github.com/anitagraser/movingpandas/blob/master/README.md)

> Note that it is NOT recommended to install MovingPandas from PyPI! If you're on Windows or Mac, many GeoPandas / MovingPandas dependencies cannot be pip installed (for details see the corresponding notes in the GeoPandas documentation). On Ubuntu, pip install fails on cartopy with "Proj 4.9.0 must be installed".

**Comment by anitagraser** [comment]
@paumillet Due to a packaging mistake, mpd.__version__ returns an old version number. Please check conda list for the correct version number.
