### ISSUE TITLE
Iterate through TrajectoryCollection

### ISSUE THREAD

**Issue by anitagraser** [anitagraser/movingpandas#69]
Would be great to be able to write

`for traj in traj_collection:`

**Comment by stevemarin** [comment]
Wouldn't this be as simple as adding the following to the `TrajectoryCollection` class?

```
def __iter__(self):
    return iter(self.trajectories)
```

Are there issues I'm missing here?

A few related questions: 

I have a use-case where I want to filter a `TrajectoryCollection` based on a time window.  I want to do something like this:
```
start = '2020-02-01'
end = '2020-02-02'

for idx in range(len(traj_collection)):
    traj_collection.trajectories[idx].df = traj_collection.trajectories[idx].df[start: end]
```

1. Do you foresee any issues modifying the `Trajectory`s of a `TrajectoryCollection` after instantiation?
2. Would there be issues if after instantiation, some of the `TrajectoryCollection`'s `Trajectory`s have empty dataframes?
3. Is it safe to remove Trajectories from a collection after instantiation?

In general, when iterating over a `TrajectoryCollection` and modifying/removing `Trajectory`s, would it be safer to just create a list of the modified list of `Trajectory`s and create a new`TrajectoryCollection`?

`TrajectoryCollection.split_by_observation_gap()` returns a new `TrajectoryCollection` created by copying the input `TrajectoryCollection` and replacing the list of `Trajectory`s with a new list.  This seems to suggest modifying the list of `Trajectory`s is okay?  Is that right?

**Comment by anitagraser** [comment]
Thanks @stevemarin! Iterating is most likely as simple as you showed, plus some time to update the documentation and tutorials accordingly. PRs are welcome, if you'd like to do it.

So far, I haven't run into any issues with replacing the list of trajectories in a collection. I think this approach should also work for filtering by start and end time. Trajectories with empty dataframes sound less ideal. I don't think we have checks for this (except for in the Trajectory constructor).

**Comment by stevemarin** [comment]
I'm happy to put this in a PR.  In terms of empty dataframes, would something like this would work:

```
def __iter__(self):
    for traj in self.trajectories:
        if not traj.df.empty:
            yield traj
```

Would you prefer also raising a warning if the df is empty?  Or some other approach completely?

**Comment by anitagraser** [comment]
I think trajectories with empty df shouldn't be allowed to exist. Or do you see a use case for such trajectory objects? For example, the trajectory constructor currently checks that there are at least two rows in the df.

**Comment by stevemarin** [comment]
I don't see a use.  So maybe `__iter__` should check each df has at least 2 points and raise an exception otherwise?  

This suggests that any function / method that could filter a df down to 0 or 1 points is responsible for removing those `Trajectory`s from the list?  Then they would follow your convention of copying the `TrajectoryCollection` and then replacing the `Trajectory`s with the modified list?

**Comment by anitagraser** [comment]
Yes, I think functions / methods that can reduce a df down to < 2 should be responsible to remove invalid trajectories (i.e. ones with fewer than 2 rows). If a collection contains invalid trajectories, something went wrong.

**Comment by anitagraser** [comment]
I've just fixed Travis. So if you want to send a PR that implements this feature, the CI should work correctly.
