### ISSUE TITLE
trajectory not plotted with `c` parameter

### ISSUE THREAD

**Issue by gma2th** [anitagraser/movingpandas#71]
In tutorial 1 on mybinder, plotting the trajectory by navigation status does not display the trajectory on the map. It works if we remove the `c` parameter.

```
my_traj.hvplot(title='Trajectory {}'.format(str(my_traj.id)), height=300, line_width=5.0, c='NavStatus', cmap='Dark2') 
```

![Screenshot 2020-05-22 at 15 14 28](https://user-images.githubusercontent.com/7457957/82641817-8cf59980-9c3f-11ea-8a8a-c3f786a252a3.png)
![Screenshot 2020-05-22 at 15 14 14](https://user-images.githubusercontent.com/7457957/82641830-9121b700-9c3f-11ea-9072-37be16bb160a.png)

**Comment by philippjfr** [comment]
The odd thing is that there has been no recent release of hvPlot, but I'm actually trying to get a release out this weekend. So I'll try to track down the issue.

**Comment by anitagraser** [comment]
Thanks @philippjfr! I'll try if removing the bokeh pin from environment.yml fixes it.

**Comment by anitagraser** [comment]
Unfortunately, that didn't help.

**Comment by anitagraser** [comment]
@philippjfr Do you have any idea why the c parameter may not be working for GeoDataframes with line geometry? As shown below, the same hvplot call works properly if the geometry is set to a points column:

![image](https://user-images.githubusercontent.com/590385/85145528-f8d21e80-b24c-11ea-8607-085a3daf0acf.png)

**Comment by anitagraser** [comment]
Reported here https://github.com/holoviz/geoviews/issues/466

**Comment by anitagraser** [comment]
As @philippjfr pointed out in https://github.com/holoviz/geoviews/issues/466, using `c=hv.dim('colname')` fixes the issue:

![image](https://user-images.githubusercontent.com/590385/88079217-b36f7c80-cb7d-11ea-8fa8-20f166738aa6.png)

I might just add that workaround to the next release ...
