### ISSUE TITLE
v0.4-rc1 Release Plan

### ISSUE THREAD

**Issue by saadsaifse** [anitagraser/movingpandas#73]
Hi, I was wondering when the next version `0.4-rc1` will be released? As the generalization related classes will be in that version. 

Right now, `conda-forge` only contains `0.3rc1` as the latest version and I am unable to install `0.4rc1`. Even though the releases tab shows a release with the name of Binder but seems like it is not available using conda. Should we build from the source until the new version, please advise!

**Comment by anitagraser** [comment]
Generalization code has been refactored in 0.4 but most functionality was already included in 0.3, see https://movingpandas.readthedocs.io/en/v0.3.rc1/trajectory.html

There is no set date for releasing 0.4 yet.

**Comment by saadsaifse** [comment]
Thank you, I completely overlooked that. Could you please explain what changed in terms of generalization algorithms? or is it only code refactoring in the new version?

**Comment by anitagraser** [comment]
Douglas-Peucker was not implemented correctly in 0.3. Now it's correct and faster. The other methods were only refactored.

**Comment by saadsaifse** [comment]
Great! will definitely be looking forward to v0.4. Thank you for your time.
