### ISSUE TITLE
Make plotting dependencies optional

### ISSUE THREAD

**Issue by anitagraser** [anitagraser/movingpandas#78]
To make installation easier an thus make MovingPandas more suitable for integration, e.g. in a QGIS plugin.

**Comment by martinfleis** [comment]
@anitagraser if you want to follow geopandas model, you need to switch to optional imports in the code and then you can do `movingpandas` and `movingpandas-base` conda recipes following https://github.com/conda-forge/geopandas-feedstock/blob/master/recipe/meta.yaml.

**Comment by martinfleis** [comment]
@anitagraser that PR is pretty extensive, a lot of those changes are not needed to do the bare minimum here. I've never used `tox` for example.

This bit is crucial, that is what I meant by optional imports.

```py
def hvplot(self):
   try:
       import hvplot.pandas  # seems to be necessary for the following import to work
       from holoviews import opts, dim
   except ImportError:
       raise ImportError('hvplot, bokeh, and geoviews must be installed for hvplot. Run `pip install "movingpandas[viz]"`')
```

If you have multiple functions that would need it, you can do this try/except once and use a decorator or some other trick to minimise duplication of code.

Once this is done, you should be able to use movingpandas without hvplot with no other changes. You can install as `pip install movingpandas --no-deps` to avoid installation of dependencies. 

The `pip install movingpandas[viz]` option as suggested in #87 is also possible, but assuming that the main installation mode is conda anyway (at least should be considering you depend on geopandas), it is not ideal. The conda recipe would be nice though :).

**Comment by raybellwaves** [comment]
Copying @anitagraser's comment from https://github.com/anitagraser/movingpandas/pull/87#issuecomment-1008020689 here

https://github.com/anitagraser/movingpandas/pull/93 added code for optional installs (inspired from xarray) which looks like:

FILE.py:
```
try:
    from MODULE import CLASS/FUNCTION
except ImportError as error:
    raise ImportError(
        "Missing optional dependencies... install MODULE "
    ) from error
```

__init__,py:
```
try:
    from .FILE import CLASS/FUNCTION  # noqa F401
except ImportError:
    pass
```

tests/__init__.py:
```
import pytest
import importlib


def _importorskip(modname):
    try:
        importlib.import_module(modname)
        has = True
    except ImportError:
        has = False
    func = pytest.mark.skipif(not has, reason=f"requires {modname}")
    return has, func


has_MODULE, requires_MODULE = _importorskip("MODULE")
```

tests/test_FILE.py:
```
@requires_MODULE
def test_...():
    pass
```

**Comment by anitagraser** [comment]
@raybellwaves I didn't change the tests yet. Not sure if it's worth testing with two different environments.

**Comment by anitagraser** [comment]
I guess we'll also need to change https://github.com/conda-forge/movingpandas-feedstock/blob/main/recipe/meta.yaml accordingly

**Comment by anitagraser** [comment]
I guess the conda recipe with reduced dependencies would fail if we don't adjust the tests, so here we go: https://github.com/anitagraser/movingpandas/commit/71defbadb09566b5989df1c8cf44353520649eb3
