### ISSUE TITLE
python3.7: LineString.cpp:121: const geos::geom::CoordinateSequence* geos::geom::LineString::getCoordinatesRO() const: Assertion `0 != points.get()' failed.

### ISSUE THREAD

**Issue by dazzag24** [anitagraser/movingpandas#81]
kernel dies on cell:

```
passenger = traj_collection.filter('ShipType', 'Passenger')
passenger.hvplot(title='Passenger ferries', line_width=2)
```

in 1_ship_data_analysis.ipynb.

in Jupyter-lab console error message is:  

```
python3.7: LineString.cpp:121: const geos::geom::CoordinateSequence* geos::geom::LineString::getCoordinatesRO() const: Assertion `0 != points.get()' failed.
```
Is this an issue with the system provided libgeos shared libs?

Note that I am running on an WSL (Windows Subsystem for Linux) Ubuntu 18.04 based system and am using pipenv to create virtual env.  Despite your comments in the README I have successfully used cartopy from pip before on Linux.  Usually you just need to apt-get install the appropriate libproj or libgeos dependency.

```
sudo apt-get install python3.7-dev

pipenv --python 3.7

pipenv shell

pipenv install --skip-lock numpy cython matplotlib seaborn pandas geopandas rasterio hvplot bokeh proj cartopy geoviews scikit-learn geopy panel

pipenv install --skip-lock jupyterlab

```

Thanks

Darren

**Comment by dazzag24** [comment]
I can now progress past that problematic cell by doing the following:

```
pip uninstall shapely

pip install shapely --no-binary shapely
```

**Comment by anitagraser** [comment]
Thank you for sharing your experience, Darren! Can you clarify whether the crash happens on the filter line or on the hvplot line?
