### ISSUE TITLE
Trajectory issues

### ISSUE THREAD

**Issue by laetokang** [anitagraser/movingpandas#82]
I'm trying to get a trajectory for each ship so I am about to use the **Trajectory** method. But there is a traj_id in it, and when I looked at the tutorial, I gave it a value of 1. I'd like to ask you why you allocated a value of 1 here. And I want to know what to do with traj_id in order to get a trajectory for each ship. Thank you.

**Comment by anitagraser** [comment]
Did you look at the ship analysis tutorial? It covers exactly that use case: https://github.com/anitagraser/movingpandas/blob/master/tutorials/1_ship_data_analysis.ipynb (MMSI is the ship identifier)

When trajectories are generated manually, we can give them any id we want. I picked 1 but any other value is fine as well.
