### ISSUE TITLE
movingpandas version 0.5 in conda-forge

### ISSUE THREAD

**Issue by stevemarin** [anitagraser/movingpandas#83]
As always, thank you very much for movingpandas!  I'm sorry if this is the wrong place to ask this.

I'm interested in the updates in version 0.5 and would love to incorporate them into my current workflow (i.e. via conda).  Do you have a rough estimate of when 0.5 might be released and when it may be available in conda-forge (days, weeks, etc.)?  Is there anything I can do to help?

Thank you!

**Comment by anitagraser** [comment]
Hi Steve,
You've come to the right place. I'm planning to do the release on the weekend. If you want to help, please have a look at the documentation to see if the new features are covered sufficiently.

**Comment by stevemarin** [comment]
Anita,

I read through the docs and read through the notebooks again.  I think the docs along with the notebooks look great.  I love how the notebooks serve as both documentation and demonstration on how to use `movingpandas`.

The only comment I have is the splitters are a __bit__ cumbersome to use.  Concretely, it took me a minute to comprehend that the trajectory went in the class instantiation and the gap (for the time gap splitter) went in the split function.  Might it be simpler to just add the splitting classes as functions to the `Trajectory` and `TrajectoryCollection` classes?  Or at least have the split function accept the traj rather than `__init__.`

Same might go for the stop detectors, plotters, and generalizers.  Seems like the aggregator is maybe complex enough to warrant it's own class.  This could all just be personal preference.  ;)

But I think the docs look great!

**Comment by anitagraser** [comment]
Thank you for the having a look and for the feedback, Steve, really appreciate it! I'll give the design of the splitters/generalizers/aggregators another round of thought before the 0.5 release. In any case, one approach that is consistent throughout MovingPandas seems preferable to make it easy to learn.

**Comment by stevemarin** [comment]
FYI, I just noticed several of the new classes (such as `TrajectoryStopDetector`) can be initialized with either a `Trajectory` or a `TrajectoryCollection`, but the docstrings only note the `Trajectory`.

**Comment by anitagraser** [comment]
Done: https://anaconda.org/conda-forge/movingpandas

![image](https://user-images.githubusercontent.com/590385/94341913-aa7fa900-000d-11eb-8f74-a330071cb537.png)
