### ISSUE TITLE
hvplot: Supplied data does not contain specified dimensions, the following dimensions were not found: ['Longitude', 'Latitude']

### ISSUE THREAD

**Issue by RihamSYElhabyan** [anitagraser/movingpandas#85]
Trying to run the tutorials and I always get an error at the hvplot line:

DataError                                 Traceback (most recent call last)
<command-777809567523750> in <module>
----> 1 df.to_crs({'init': 'epsg:4326'}).hvplot(title='Geographic extent of the dataset', geo=True, tiles='OSM', width=500, height=500)

/databricks/python/lib/python3.7/site-packages/hvplot/plotting/core.py in __call__(self, x, y, kind, **kwds)
     70                 return pn.panel(plot, **panel_dict)
     71 
---> 72         return self._get_converter(x, y, kind, **kwds)(kind, x, y)
     73 
     74     def _get_converter(self, x=None, y=None, kind=None, **kwds):

/databricks/python/lib/python3.7/site-packages/hvplot/converter.py in __call__(self, kind, x, y)
   1011                     columns = [c for c in data.columns if c != 'geometry']
   1012                     shape_dims = ['Longitude', 'Latitude'] if self.geo else ['x', 'y']
-> 1013                     dataset = Dataset(data, kdims=shape_dims+columns)
   1014                 elif self.datatype == 'xarray':
   1015                     import xarray as xr

/databricks/python/lib/python3.7/site-packages/holoviews/core/data/__init__.py in __init__(self, data, kdims, vdims, **kwargs)
    352         (data, self.interface, dims, extra_kws) = initialized
    353         super(Dataset, self).__init__(data, **dict(kwargs, **dict(dims, **extra_kws)))
--> 354         self.interface.validate(self, validate_vdims)
    355 
    356         # Handle _pipeline property

/databricks/python/lib/python3.7/site-packages/holoviews/core/data/pandas.py in validate(cls, dataset, vdims)
    155             raise DataError("Supplied data does not contain specified "
    156                             "dimensions, the following dimensions were "
--> 157                             "not found: %s" % repr(not_found), cls)
    158 
    159 

DataError: Supplied data does not contain specified dimensions, the following dimensions were not found: ['Longitude', 'Latitude']

PandasInterface expects tabular data, for more information on supported datatypes see http://holoviews.org/user_guide/Tabular_Datasets.html

**Comment by anitagraser** [comment]
I cannot reproduce the issue locally or on mybinder. Please include information about the involved library versions, particularly hvplot and holoviews. It may be that databricks uses other/older versions than expected.

**Comment by RihamSYElhabyan** [comment]
holoviews 1.13.4
hvplot  0.6.0
bokeh  2.1.1  

This is the complete result of pip list in my notebook:

Package                      Version            
---------------------------- -------------------
absl-py                      0.9.0              
argon2-cffi                  20.1.0             
asn1crypto                   1.3.0              
astor                        0.8.0              
astunparse                   1.6.3              
attrs                        20.2.0             
azure-core                   1.7.0              
azure-storage-blob           12.3.2             
backcall                     0.1.0              
bcrypt                       3.1.7              
bleach                       3.2.1              
blinker                      1.4                
**bokeh                        2.1.1**              
boto3                        1.12.0             
botocore                     1.15.0             
cachetools                   4.1.0              
Cartopy                      0.17.0             
certifi                      2020.6.20          
cffi                         1.14.0             
chardet                      3.0.4              
Click                        7.0                
click-plugins                1.1.1              
cligj                        0.5.0              
cloudpickle                  1.3.0              
colorcet                     2.0.1              
configparser                 3.7.4              
cryptography                 2.8                
cycler                       0.10.0             
Cython                       0.29.15            
databricks-cli               0.11.0             
decorator                    4.4.1              
defusedxml                   0.6.0              
dill                         0.3.1.1            
diskcache                    4.1.0              
docker                       4.2.2              
docutils                     0.15.2             
entrypoints                  0.3                
Fiona                        1.8.4              
Flask                        1.1.1              
future                       0.18.2             
gast                         0.3.3              
GDAL                         2.3.3              
geopandas                    0.6.3              
geoviews                     1.5.0             
gitdb                        4.0.5              
GitPython                    3.1.0              
google-auth                  1.11.2             
google-auth-oauthlib         0.4.1              
google-pasta                 0.2.0              
gorilla                      0.3.0              
grpcio                       1.27.2             
gunicorn                     20.0.4             
h5py                         2.10.0             
**holoviews                    1.13.4**             
horovod                      0.19.5             
**hvplot                       0.6.0**              
hyperopt                     0.2.4.db2          
idna                         2.8                
importlib-metadata           2.0.0              
ipykernel                    5.1.4              
ipython                      7.12.0             
ipython-genutils             0.2.0              
ipywidgets                   7.5.1              
isodate                      0.6.0              
itsdangerous                 1.1.0              
jedi                         0.14.1             
Jinja2                       2.11.1             
jmespath                     0.10.0             
joblib                       0.14.1             
joblibspark                  0.2.0              
jsonschema                   3.2.0              
jupyter-client               5.3.4              
jupyter-console              6.2.0              
jupyter-core                 4.6.1              
Keras-Preprocessing          1.1.2              
kiwisolver                   1.1.0              
koalas                       1.1.0              
lightgbm                     2.3.0              
Mako                         1.1.2              
Markdown                     3.1.1              
MarkupSafe                   1.1.1              
matplotlib                   3.1.3              
mistune                      0.8.4              
mkl-fft                      1.0.15             
mkl-random                   1.1.0              
mkl-service                  2.3.0              
mleap                        0.16.1             
mlflow                       1.9.1              
movingpandas                 0.5rc1             
msrest                       0.6.17             
munch                        2.5.0              
nbconvert                    5.6.1              
nbformat                     5.0.7              
networkx                     2.4                
nltk                         3.4.5              
notebook                     6.1.4              
numpy                        1.18.1             
oauthlib                     3.1.0              
olefile                      0.46               
opt-einsum                   3.3.0              
OWSLib                       0.19.2             
packaging                    20.1               
pandas                       1.0.1              
pandocfilters                1.4.2              
panel                        0.9.7              
param                        1.9.3              
paramiko                     2.7.1              
parso                        0.5.2              
patsy                        0.5.1              
petastorm                    0.9.2              
pexpect                      4.8.0              
pickleshare                  0.7.5              
Pillow                       7.0.0              
pip                          20.0.2             
plotly                       4.8.2              
prometheus-client            0.8.0              
prompt-toolkit               3.0.3              
protobuf                     3.11.4             
psutil                       5.6.7              
psycopg2                     2.8.4              
ptyprocess                   0.6.0              
pyarrow                      0.15.1             
pyasn1                       0.4.8              
pyasn1-modules               0.2.7              
pycparser                    2.19               
pyct                         0.4.6              
pyepsg                       0.4.0              
Pygments                     2.5.2              
PyJWT                        1.7.1              
pykdtree                     1.3.1              
PyNaCl                       1.3.0              
pyodbc                       4.0.0-unsupported  
pyOpenSSL                    19.1.0             
pyparsing                    2.4.6              
pyproj                       1.9.6              
pyrsistent                   0.17.3             
pyshp                        2.1.2              
PySocks                      1.7.1              
python-dateutil              2.8.1              
python-editor                1.0.4              
pytz                         2019.3             
pyviz-comms                  0.7.6              
PyYAML                       5.3.1              
pyzmq                        18.1.1             
qtconsole                    4.7.7              
QtPy                         1.9.0              
querystring-parser           1.2.4              
requests                     2.22.0             
requests-oauthlib            1.3.0              
retrying                     1.3.3              
rsa                          4.0                
Rtree                        0.9.4              
s3transfer                   0.3.3              
scikit-learn                 0.22.1             
scipy                        1.4.1              
seaborn                      0.10.0             
Send2Trash                   1.5.0              
setuptools                   45.2.0.post20200210
Shapely                      1.6.4.post2        
simplejson                   3.17.0             
six                          1.14.0             
smmap                        3.0.2              
spark-tensorflow-distributor 0.1.0              
sparkdl                      2.1.0-db1          
sqlparse                     0.3.0              
statsmodels                  0.11.0             
tabulate                     0.8.3              
tensorboard                  2.2.2              
tensorboard-plugin-wit       1.7.0              
tensorflow-cpu               2.2.0              
tensorflow-estimator         2.2.0              
termcolor                    1.1.0              
terminado                    0.9.1              
testpath                     0.4.4              
torch                        1.5.1              
torchvision                  0.6.0a0+35d732a    
tornado                      6.0.3              
tqdm                         4.42.1             
traitlets                    4.3.3              
typing-extensions            3.7.4.2            
urllib3                      1.25.8             
wcwidth                      0.1.8              
webencodings                 0.5.1              
websocket-client             0.56.0             
Werkzeug                     1.0.0              
wheel                        0.34.2             
widgetsnbextension           3.5.1              
wrapt                        1.11.2             
xgboost                      1.1.1              
zipp                         3.3.0   

Thanks

**Comment by RihamSYElhabyan** [comment]
To give an update: I have installed geoviews using pip install geoviews==1.8.1 and now I am not getting the same error however nothing is showing. I will debug that.

It seems that using PYPI in databricks is failing to download the latest version of geoviews.
