### ISSUE TITLE
Passing ax argument when plotting trajectory collection does not work

### ISSUE THREAD

**Issue by sglvladi** [anitagraser/movingpandas#88]
Hi there,

While playing around with the tutorials, I noticed that trying to plot trajectory collections on designated axis handles does not work as expected. To showcase the problem, let's consider the following example:

```python
# imports and definition of traj_collection and smooth_traj_collection skipped to save space

fig, axes = plt.subplots(nrows=1, ncols=2, figsize=(16,4))
traj_collection.plot(ax=axes[0], column='speed', linewidth=5, capstyle='round', legend=True, vmax=20)
axes[0].set_title('Original Trajectories')
smooth_traj_collection.plot(ax=axes[1], column='speed', linewidth=5, capstyle='round', legend=True, vmax=20)
axes[1].set_title('Smooth Trajectories')
```

Based on the above code segment, the expected output would be the following:

![image](https://user-images.githubusercontent.com/11223208/95934767-92f43e80-0dc9-11eb-8a3b-904e7133defb.png)

However, this is what is observed instead:
![image](https://user-images.githubusercontent.com/11223208/95934627-3abd3c80-0dc9-11eb-9c36-e87c9f590bf9.png)

I was able to fix the issue by applying a minor change to [line 102 of trajectory_plotter.py](https://github.com/anitagraser/movingpandas/compare/master...sglvladi:trajectory_plotter_fix?diff=split#diff-82c5821b2fccaa070551aae8fabe0adc8cc8c56618ed15e5b117fb1c6c7b6f4dR102). If this seems like a reasonable change, I'll be happy to create a PR. However I wanted to check first to make sure that this is an actual issue and not a "feature".

**Comment by anitagraser** [comment]
Hi Lyudmil, thanks for raising this issue! I ran into it myself recently and agree that it should be fixed. Your proposal looks good to me. Feel free to create a PR.

**Comment by sglvladi** [comment]
@anitagraser Thanks for the swift response. I'll proceed to create a PR now 👍
