### ISSUE TITLE
TrajectoryCollection plotter alters speed column

### ISSUE THREAD

**Issue by sglvladi** [anitagraser/movingpandas#90]
Hi there,

While doing some work with trajectory collections, I came across something that had me scratching my head for quite a while. In order to explain my issue, let me introduce the following examples, where we check the columns of the trajectory dataframes before and after plotting with ``column='speed``. First, let's examine a ``Trajectory`` object, for reference:

```python
traj_collection = mpd.TrajectoryCollection(df, 'trajectory_id')
traj = traj_collection.trajectories[0]
# Before plotting
traj.df.columns.values
Out[1]: array(['id', 'sequence', 'trajectory_id', 'tracker', 'geometry'], dtype=object)
traj.plot(column='speed', linewidth=5, capstyle='round', legend=True, vmax=20)
# After plotting
traj.df.columns.values
Out[2]: array(['id', 'sequence', 'trajectory_id', 'tracker', 'geometry'], dtype=object)
```
Good: As we can see above, the plotter does not modify the object in any way.

Now let's move on to the ``TrajectoryCollection``. To preserve space, I'll only consider the first trajectory, but the same applies to all trajectories in the collection:
``` python
# Before plotting
traj_collection.trajectories[0].df.columns.values
Out[3]: array(['id', 'sequence', 'trajectory_id', 'tracker', 'geometry'], dtype=object)
traj_collection.plot(column='speed', linewidth=5, capstyle='round', legend=True, vmax=20)
# After plotting
traj_collection.trajectories[0].df.columns.values
Out[4]: array(['id', 'sequence', 'trajectory_id', 'tracker', 'geometry', 'speed'], dtype=object)
```
**Problem:** The plotter has now added the ``speed`` column to all trajectories in the collection.

To understand why this is a problem, consider the following example:
```python
traj_collection = mpd.TrajectoryCollection(df, 'trajectory_id')
# Generalise before plotting
generalized1 = mpd.MinDistanceGeneralizer(traj_collection).generalize(tolerance=1000)
# Plot
traj_collection.plot(column='speed', linewidth=5, capstyle='round', legend=True, vmax=20)
# Generalise after plotting
generalized2 = mpd.MinDistanceGeneralizer(traj_collection).generalize(tolerance=1000)
# Plot the two generalized collections with column='speed'
fig, axes = plt.subplots(nrows=1, ncols=2, figsize=(16,4))
generalized1.plot(ax=axes[0], column='speed', linewidth=5, capstyle='round', legend=True, vmax=20)
axes[0].set_title('Generalised 1')
generalized2.plot(ax=axes[1], column='speed', linewidth=5, capstyle='round', legend=True, vmax=20)
axes[1].set_title('Generalised 2')
plt.show()
```
![image](https://user-images.githubusercontent.com/11223208/96050045-e79ec480-0e70-11eb-90e3-68e524741673.png)

Even though both `generalized1` and `generalized2` should be the same (and in a sense they are), when plotted, the displayed speed is different. This is because in the case of `generalized1` the speed is calculated when `generalized1.plot()` is called, while `generalized2.plot()` skips the calculation (see [here](https://github.com/anitagraser/movingpandas/blob/d72141e1a3a22fcaeede77f32bdb7417b5280a45/movingpandas/trajectory_plotter.py#L93)) since the `speed` column already exists from when `traj_collection.plot()` was called.

A fix for the above can be achieved by making sure that plotters only operate on copies of the provided data, whether that is a single trajectory or a collection. A possible fix can be found [here](https://github.com/anitagraser/movingpandas/compare/master...sglvladi:trajectory_collection_copy_and_plotter_fix?expand=1). I can create a PR if this seems like a sensible solution.

**Comment by anitagraser** [comment]
Thanks for catching this issue! TrajectoryCollections should definitely behave like Trajectories, i.e. plotting them should operate on copies and not change the trajectories. 

Considering the fix, I wonder if there's a way to avoid copying the whole TrajectoryCollection and instead only copy one Trajectory after the other ... but that might cause other issues.

**Comment by sglvladi** [comment]
> Considering the fix, I wonder if there's a way to avoid copying the whole TrajectoryCollection and instead only copy one Trajectory after the other ... but that might cause other issues.

Copying the trajectories one-by-one should be possible, but it would still be necessary to store a copy of each trajectory so that `min_max` values can be computed. It also bears the risk that future additions may re-introduce the same problem. Instead if a copy is acquired on instantiation, that copy can be freely modified without affecting the original version.

As it stands, unless I am missing something, copying the collection is very much equivalent to copying the underlying trajectories and then creating a new collection (see [the introduced `copy()` method](https://github.com/anitagraser/movingpandas/compare/master...sglvladi:trajectory_collection_copy_and_plotter_fix?expand=1#diff-c35cd294b722386eca05695a582e21cb202526854ce2a0abad6fca6fce74b12fR77)). Is there a specific reason why copying the collection may be undesirable?

**Comment by anitagraser** [comment]
I was thinking of higher memory usage

**Comment by sglvladi** [comment]
Ahh, that's true. Indeed this could be a problem for very large collections. 

OK.  Here's an alternative that works on a trajectory by trajectory basis:

```python
class _TrajectoryCollectionPlotter(_TrajectoryPlotter):
    def __init__(self, data, *args, **kwargs):
        super().__init__(data, *args, **kwargs)
        self._speeds = []

    def get_min_max_values(self):
        speed_col_name = self.data.trajectories[0].get_speed_column_name()
        min_value, max_value = (None, None)
        if self.column == speed_col_name:
            for traj in self.data:
                if self.column not in traj.df.columns:
                    temp = traj.copy()
                    temp.add_speed(overwrite=True)
                    self._speeds.append(temp.df[self.column])
                else:
                    self._speeds.append(traj.df[self.column])
            min_value = min([min(s.tolist()) for s in self._speeds])
            max_value = max([max(s.tolist()) for s in self._speeds])
        self.min_value = self.kwargs.pop('vmin', min_value)
        self.max_value = self.kwargs.pop('vmax', max_value)

    def plot(self):
        if self.column:
            self.get_min_max_values()

        if not self.ax:
            self.ax = plt.figure(figsize=self.figsize).add_subplot(1, 1, 1)

        for i, traj in enumerate(self.data):
            speed_col_name = traj.get_speed_column_name()
            if self.column == speed_col_name and self.column not in traj.df.columns:
                temp = traj.copy()
                temp.df[self.column] = self._speeds[i]
                self.ax = self._plot_trajectory(temp)
            else:
                self.ax = self._plot_trajectory(traj)
            self.kwargs['legend'] = False  # has to be removed after the first iteration, otherwise we get multiple legends!

        self.kwargs.pop('column', None)  # has to be popped, otherwise there's an error in the following plot call if we don't remove column from kwargs
        start_locs = self.data.get_start_locations()
        ax = start_locs.plot(ax=self.ax, column=self.column, color='white', *self.args, **self.kwargs)
        return ax
...
```

The above avoids the need for copying a collection and seems to work just as well. The changes applied are:
- The addition of `_speeds` property which is used to cache the speeds computed when calculating the minmax conditions, so as to avoid recalculation later.
- `get_min_max_values()` now computes the speeds and minmax conditions, storing the former in `_speeds`
- Prior to plotting a trajecotry, if the `speed` column is missing in its dataframe, a copy is created and the cached speed is added.

Let me know what you think.

**Comment by anitagraser** [comment]
Thanks, that should do the trick. The functions are becoming a bit unwieldy but I can address that in a follow-up refactoring step.

**Comment by anitagraser** [comment]
Please feel free to send a PR.
