### ISSUE TITLE
Overlay point coordinates wrongly displayed on hovering

### ISSUE THREAD

**Issue by Vikas-Singh-Negi** [anitagraser/movingpandas#94]
Hi Anita
Thanks for your feedback on the hover issue.
I have my own GPS data with few placemarkers and CRS is EPSG 4326.
While I overlay these points in place markers on top of trajectory hvplot() , hovering works for them, but it looks like coordinates displayed while hovering are not in accordance to GPS data.

Regards
Vikas

**Comment by anitagraser** [comment]
MovingPandas uses Holoviews Geoviews for (hvplot) plotting. Any issues with non-trajectory data you're trying to plot should be reported directly to the Geoviews devs. 

In the above mentioned case, it may be that you're missing the `geo=True` parameter when plotting lat/lon but the ticket would need a reproducible example to be sure.

**Comment by Vikas-Singh-Negi** [comment]
Thanks Anita for the direction. Yes I did kept geo as True. I will log this
holoviews.
I have no prior experience of holoviews and only got introduced via
movingpandas so thought it might be something related to it.
Your time to revert is highly appreciated.
