### ISSUE TITLE
Export trajectories to CSV

### ISSUE THREAD

**Issue by jiaoleixin** [anitagraser/movingpandas#98]
How can I write trajectory data to a file? like shp or csv. And I couldn't find any method to write a <shapely.LineString> into shapefile, either.
I'm a beginner in GIS.
Please give me a hand. THX

**Comment by anitagraser** [comment]
One option would be to write the WKT representation of the trajectory to a CSV file.

In the future, this could be a built-in function of the TrajectoryCollection class.

**Comment by anitagraser** [comment]
See #114 for details about the new implementation. It allows users to convert Trajectory or TrajectoryCollection objects to different types of GeoDataFrame that can then be exported using GeoPandas IO https://geopandas.org/docs/user_guide/io.html
